2024-05-27 18:08:08,958:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 18:08:13,622:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 18:08:15,263:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 18:09:07,656:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 18:10:25,552:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/profiles/models.py changed, reloading.)
2024-05-27 18:10:35,335:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 18:10:43,148:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 18:10:51,990:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 18:11:18,802:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 18:11:30,870:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 19:35:28,533:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/serializers.py changed, reloading.)
2024-05-27 19:35:31,646:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 19:35:35,608:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 19:37:41,209:WARNING - django.request log.py (line 241. Not Found: /favicon.ico)
2024-05-27 19:38:22,154:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 20:02:40,612:WARNING - django.request log.py (line 241. Not Found: /api/v1/playlists/)
2024-05-27 20:06:21,895:WARNING - django.request log.py (line 241. Not Found: /api/v1/playlists/)
2024-05-27 20:08:00,682:INFO - django.utils.autoreload autoreload.py (line 266. /app/config/urls.py changed, reloading.)
2024-05-27 20:08:04,600:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 20:08:05,842:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 20:08:33,762:WARNING - django.request log.py (line 241. Not Found: /api/v1/playlists/)
2024-05-27 20:08:57,109:INFO - django.utils.autoreload autoreload.py (line 266. /app/config/urls.py changed, reloading.)
2024-05-27 20:09:02,805:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 20:09:04,856:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 20:09:11,140:WARNING - django.request log.py (line 241. Not Found: /api/v1/playlists/)
2024-05-27 20:09:18,833:WARNING - django.request log.py (line 241. Not Found: /api/v1/anim/)
2024-05-27 20:10:39,921:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 20:10:42,175:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 20:10:44,140:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 20:10:58,165:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 20:11:02,721:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 20:11:04,341:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 20:11:20,994:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 20:11:24,111:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 20:11:25,808:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 20:11:38,157:WARNING - django.request log.py (line 241. Not Found: /api/v1/playlists/)
2024-05-27 20:12:20,520:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/routers.py changed, reloading.)
2024-05-27 20:12:23,878:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 20:12:25,210:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 20:12:33,394:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/playlists/)
2024-05-27 20:12:34,868:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/playlists/)
2024-05-27 20:12:45,032:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 20:12:47,710:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 20:12:49,226:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 20:12:51,117:ERROR - django.request log.py (line 241. Internal Server Error: /api/v1/playlists/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2747, in to_python
    return uuid.UUID(**{input_form: value})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/uuid.py", line 175, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
          ^^^^^^^^^^^
AttributeError: 'AnonymousUser' object has no attribute 'replace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "/app/apps/playlists/viewsets.py", line 27, in get_queryset
    return Playlist.objects.filter(user=self.request.user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1602, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1634, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1548, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1378, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/fields/related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2731, in get_prep_value
    return self.to_python(value)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2749, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“AnonymousUser” is not a valid UUID.']
2024-05-27 20:13:21,959:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 20:13:25,212:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 20:13:26,416:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 20:13:31,301:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 20:13:33,592:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 20:13:34,804:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 20:13:40,995:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 20:13:42,910:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 20:13:43,865:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 20:16:17,114:WARNING - django.request log.py (line 241. Bad Request: /api/v1/users/)
2024-05-27 20:18:09,893:WARNING - django.request log.py (line 241. Bad Request: /api/v1/users/activation/)
2024-05-27 20:19:02,688:WARNING - django.request log.py (line 241. Bad Request: /api/v1/tokens/jwt/create/)
2024-05-27 20:21:33,184:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/tokens/jwt/create/)
2024-05-27 20:21:50,243:WARNING - django.request log.py (line 241. Forbidden: /api/v1/users/activation/)
2024-05-27 20:32:30,110:DEBUG - PIL.Image Image.py (line 363. Importing BlpImagePlugin)
2024-05-27 20:32:30,113:DEBUG - PIL.Image Image.py (line 363. Importing BmpImagePlugin)
2024-05-27 20:32:30,114:DEBUG - PIL.Image Image.py (line 363. Importing BufrStubImagePlugin)
2024-05-27 20:32:30,116:DEBUG - PIL.Image Image.py (line 363. Importing CurImagePlugin)
2024-05-27 20:32:30,118:DEBUG - PIL.Image Image.py (line 363. Importing DcxImagePlugin)
2024-05-27 20:32:30,122:DEBUG - PIL.Image Image.py (line 363. Importing DdsImagePlugin)
2024-05-27 20:32:30,132:DEBUG - PIL.Image Image.py (line 363. Importing EpsImagePlugin)
2024-05-27 20:32:30,136:DEBUG - PIL.Image Image.py (line 363. Importing FitsImagePlugin)
2024-05-27 20:32:30,140:DEBUG - PIL.Image Image.py (line 363. Importing FliImagePlugin)
2024-05-27 20:32:30,142:DEBUG - PIL.Image Image.py (line 363. Importing FpxImagePlugin)
2024-05-27 20:32:30,146:DEBUG - PIL.Image Image.py (line 366. Image: failed to import FpxImagePlugin: No module named 'olefile')
2024-05-27 20:32:30,146:DEBUG - PIL.Image Image.py (line 363. Importing FtexImagePlugin)
2024-05-27 20:32:30,149:DEBUG - PIL.Image Image.py (line 363. Importing GbrImagePlugin)
2024-05-27 20:32:30,153:DEBUG - PIL.Image Image.py (line 363. Importing GifImagePlugin)
2024-05-27 20:32:30,154:DEBUG - PIL.Image Image.py (line 363. Importing GribStubImagePlugin)
2024-05-27 20:32:30,157:DEBUG - PIL.Image Image.py (line 363. Importing Hdf5StubImagePlugin)
2024-05-27 20:32:30,159:DEBUG - PIL.Image Image.py (line 363. Importing IcnsImagePlugin)
2024-05-27 20:32:30,169:DEBUG - PIL.Image Image.py (line 363. Importing IcoImagePlugin)
2024-05-27 20:32:30,171:DEBUG - PIL.Image Image.py (line 363. Importing ImImagePlugin)
2024-05-27 20:32:30,174:DEBUG - PIL.Image Image.py (line 363. Importing ImtImagePlugin)
2024-05-27 20:32:30,179:DEBUG - PIL.Image Image.py (line 363. Importing IptcImagePlugin)
2024-05-27 20:32:30,182:DEBUG - PIL.Image Image.py (line 363. Importing JpegImagePlugin)
2024-05-27 20:32:30,182:DEBUG - PIL.Image Image.py (line 363. Importing Jpeg2KImagePlugin)
2024-05-27 20:32:30,183:DEBUG - PIL.Image Image.py (line 363. Importing McIdasImagePlugin)
2024-05-27 20:32:30,185:DEBUG - PIL.Image Image.py (line 363. Importing MicImagePlugin)
2024-05-27 20:32:30,188:DEBUG - PIL.Image Image.py (line 366. Image: failed to import MicImagePlugin: No module named 'olefile')
2024-05-27 20:32:30,189:DEBUG - PIL.Image Image.py (line 363. Importing MpegImagePlugin)
2024-05-27 20:32:30,190:DEBUG - PIL.Image Image.py (line 363. Importing MpoImagePlugin)
2024-05-27 20:32:30,213:DEBUG - PIL.Image Image.py (line 363. Importing MspImagePlugin)
2024-05-27 20:32:30,216:DEBUG - PIL.Image Image.py (line 363. Importing PalmImagePlugin)
2024-05-27 20:32:30,222:DEBUG - PIL.Image Image.py (line 363. Importing PcdImagePlugin)
2024-05-27 20:32:30,224:DEBUG - PIL.Image Image.py (line 363. Importing PcxImagePlugin)
2024-05-27 20:32:30,225:DEBUG - PIL.Image Image.py (line 363. Importing PdfImagePlugin)
2024-05-27 20:32:30,239:DEBUG - PIL.Image Image.py (line 363. Importing PixarImagePlugin)
2024-05-27 20:32:30,240:DEBUG - PIL.Image Image.py (line 363. Importing PngImagePlugin)
2024-05-27 20:32:30,241:DEBUG - PIL.Image Image.py (line 363. Importing PpmImagePlugin)
2024-05-27 20:32:30,242:DEBUG - PIL.Image Image.py (line 363. Importing PsdImagePlugin)
2024-05-27 20:32:30,245:DEBUG - PIL.Image Image.py (line 363. Importing QoiImagePlugin)
2024-05-27 20:32:30,249:DEBUG - PIL.Image Image.py (line 363. Importing SgiImagePlugin)
2024-05-27 20:32:30,252:DEBUG - PIL.Image Image.py (line 363. Importing SpiderImagePlugin)
2024-05-27 20:32:30,254:DEBUG - PIL.Image Image.py (line 363. Importing SunImagePlugin)
2024-05-27 20:32:30,256:DEBUG - PIL.Image Image.py (line 363. Importing TgaImagePlugin)
2024-05-27 20:32:30,259:DEBUG - PIL.Image Image.py (line 363. Importing TiffImagePlugin)
2024-05-27 20:32:30,260:DEBUG - PIL.Image Image.py (line 363. Importing WebPImagePlugin)
2024-05-27 20:32:30,268:DEBUG - PIL.Image Image.py (line 363. Importing WmfImagePlugin)
2024-05-27 20:32:30,270:DEBUG - PIL.Image Image.py (line 363. Importing XbmImagePlugin)
2024-05-27 20:32:30,274:DEBUG - PIL.Image Image.py (line 363. Importing XpmImagePlugin)
2024-05-27 20:32:30,286:DEBUG - PIL.Image Image.py (line 363. Importing XVThumbImagePlugin)
2024-05-27 20:47:20,233:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 20:47:23,044:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 20:47:24,134:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 20:47:29,999:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 20:47:32,411:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 20:47:33,399:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 20:47:37,021:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 20:47:39,107:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 20:47:40,444:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 20:48:03,704:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 20:48:05,861:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 20:48:07,319:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 20:48:12,121:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 20:48:14,856:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 20:48:16,479:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 20:48:20,969:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 20:48:23,611:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 20:48:24,839:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 20:51:03,119:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 20:51:05,578:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 20:51:06,710:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 20:51:11,616:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 20:51:14,292:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 20:51:15,445:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 20:51:19,818:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 20:51:22,607:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 20:51:23,763:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 20:55:03,076:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 20:55:05,428:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 20:55:06,575:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 20:55:17,387:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 20:55:19,657:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 20:55:20,799:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 20:55:29,683:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 20:55:32,430:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 20:55:33,856:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:00:21,468:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:00:24,001:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:00:25,441:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:00:44,687:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:00:46,852:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:00:47,949:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:00:54,648:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:00:57,167:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:00:58,377:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:03:39,549:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:03:42,299:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:03:43,433:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:04:03,103:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:04:06,349:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:04:07,623:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:04:11,244:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:04:13,630:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:04:14,752:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:09:56,447:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:10:00,512:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:10:01,743:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:12:32,687:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:12:35,027:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:12:36,443:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:13:44,663:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:13:48,540:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:13:50,883:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:13:57,236:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:14:00,336:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:14:01,709:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:15:43,753:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:15:46,289:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:15:47,538:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:17:08,145:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:17:10,966:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:17:12,534:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:17:36,456:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:17:39,422:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:17:40,671:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:18:11,840:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:18:15,496:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:18:17,238:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:18:29,619:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:18:32,437:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:18:33,915:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:18:47,844:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:18:50,433:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:18:51,960:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:18:56,360:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:18:59,899:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:19:01,147:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:19:21,043:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:19:24,714:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:19:26,626:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:19:32,855:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:19:36,004:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:19:37,724:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:19:46,394:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:19:49,164:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:19:51,313:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:20:03,939:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:20:07,010:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:20:08,671:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:20:16,696:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:20:19,791:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:20:21,158:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:22:13,908:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:22:19,003:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:22:20,425:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:22:29,739:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:22:32,774:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:22:34,075:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:23:15,629:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:23:17,870:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:23:18,895:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:24:12,630:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:24:17,158:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:24:18,913:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:24:31,526:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:24:34,119:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:24:35,378:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:25:44,035:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:25:46,596:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:25:47,907:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:25:56,274:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:25:59,665:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:26:01,235:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:27:42,267:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:27:45,273:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:27:46,880:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:27:56,509:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:28:01,740:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:28:03,687:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:28:09,384:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:28:12,072:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:28:14,531:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:28:21,523:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:28:25,948:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:28:27,778:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:28:34,630:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:28:38,326:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:28:39,891:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:28:48,148:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:28:51,184:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:28:53,714:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:29:08,496:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:29:14,313:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:29:15,970:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:29:24,347:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:29:28,720:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:29:30,877:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:29:40,078:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:29:43,280:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:29:44,605:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:29:50,149:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:29:53,898:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:29:56,320:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:29:58,958:ERROR - django.request log.py (line 241. Internal Server Error: /api/v1/playlists/9a7124a0-1c8e-436d-b551-85fccb2e2a28/items/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/renderers.py", line 99, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Playlist is not JSON serializable
2024-05-27 21:30:24,645:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:30:31,908:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:30:35,743:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:30:56,569:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:31:04,452:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:31:06,327:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:31:11,895:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:31:15,658:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:31:17,450:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:31:25,001:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:31:28,632:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:31:30,266:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:33:36,498:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:33:39,944:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:33:41,116:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:33:57,804:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:34:02,077:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:34:03,331:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:34:35,873:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/admin.py changed, reloading.)
2024-05-27 21:34:38,689:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:34:40,169:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:36:03,816:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/models.py changed, reloading.)
2024-05-27 21:36:06,486:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:36:07,648:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:45:24,277:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:45:26,295:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:45:27,161:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:45:34,416:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:45:36,406:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:45:37,297:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:46:03,066:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:46:05,107:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:46:06,571:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:46:12,427:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/viewsets.py changed, reloading.)
2024-05-27 21:46:15,719:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:46:17,018:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:49:11,530:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/serializers.py changed, reloading.)
2024-05-27 21:49:13,799:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:49:14,696:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 21:49:21,151:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/serializers.py changed, reloading.)
2024-05-27 21:49:23,818:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 21:49:25,604:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-27 22:51:18,346:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 22:51:29,676:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-27 22:51:31,670:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 13:52:21,494:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 13:52:34,118:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 13:52:35,086:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 13:53:09,871:ERROR - django.request log.py (line 241. Internal Server Error: /api/v1/animes/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/vary.py", line 31, in _view_wrapper
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/apps/contents/viewsets.py", line 65, in list
    return super().list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 687, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "/app/apps/contents/serializers.py", line 67, in get_year
    return int(obj.season.year if obj.season else None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2024-05-28 13:53:44,243:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/playlists/)
2024-05-28 13:53:57,209:ERROR - django.request log.py (line 241. Internal Server Error: /api/v1/animes/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/vary.py", line 31, in _view_wrapper
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/apps/contents/viewsets.py", line 65, in list
    return super().list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 687, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "/app/apps/contents/serializers.py", line 67, in get_year
    return int(obj.season.year if obj.season else None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2024-05-28 13:56:31,988:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/serializers.py changed, reloading.)
2024-05-28 13:56:35,834:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 13:56:37,992:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 13:56:42,265:ERROR - django.request log.py (line 241. Internal Server Error: /api/v1/animes/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/vary.py", line 31, in _view_wrapper
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/apps/contents/viewsets.py", line 65, in list
    return super().list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 687, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "/app/apps/contents/serializers.py", line 58, in get_year
    return int(obj.season.year if obj.season else None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2024-05-28 13:57:11,472:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/serializers.py changed, reloading.)
2024-05-28 13:57:15,547:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 13:57:16,952:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 13:59:22,416:ERROR - django.request log.py (line 241. Internal Server Error: /api/v1/animes/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/vary.py", line 31, in _view_wrapper
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/apps/contents/viewsets.py", line 65, in list
    return super().list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 687, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "/app/apps/contents/serializers.py", line 67, in get_year
    return int(obj.season.year if obj.season else None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2024-05-28 14:00:53,727:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/serializers.py changed, reloading.)
2024-05-28 14:00:55,709:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:00:56,901:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:01:01,444:ERROR - django.request log.py (line 241. Internal Server Error: /api/v1/animes/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/vary.py", line 31, in _view_wrapper
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/apps/contents/viewsets.py", line 65, in list
    return super().list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 687, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/fields.py", line 1837, in to_representation
    method = getattr(self.parent, self.method_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AnimeListSerializer' object has no attribute 'get_year'
2024-05-28 14:03:48,191:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/serializers.py changed, reloading.)
2024-05-28 14:03:54,831:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:03:57,495:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:04:05,089:ERROR - django.request log.py (line 241. Internal Server Error: /api/v1/animes/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/vary.py", line 31, in _view_wrapper
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/apps/contents/viewsets.py", line 65, in list
    return super().list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 687, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `year` is not valid for model `Anime`.
2024-05-28 14:04:44,866:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/serializers.py changed, reloading.)
2024-05-28 14:04:48,378:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:04:50,380:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:06:09,605:WARNING - django.request log.py (line 241. Not Found: /api/)
2024-05-28 14:06:09,857:WARNING - django.request log.py (line 241. Not Found: /favicon.ico)
2024-05-28 14:09:40,831:ERROR - django.request log.py (line 241. Internal Server Error: /api/v1/animes/1f239e27-08be-4b30-80fe-877283a61e4c/reviews/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedTable: relation "reviews_review" does not exist
LINE 1: SELECT 1 AS "a" FROM "reviews_review" WHERE ("reviews_review...
                             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/apps/contents/viewsets.py", line 110, in review_list
    if reviews.exists():
       ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1286, in exists
    return self.query.has_results(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 648, in has_results
    return compiler.has_results()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1530, in has_results
    return bool(self.execute_sql(SINGLE))
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute
    raise ex.with_traceback(None)
django.db.utils.ProgrammingError: relation "reviews_review" does not exist
LINE 1: SELECT 1 AS "a" FROM "reviews_review" WHERE ("reviews_review...
                             ^
2024-05-28 14:13:24,567:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:13:27,289:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:13:28,602:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:13:45,396:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:13:49,571:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:13:52,443:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:14:05,227:ERROR - django.request log.py (line 241. Internal Server Error: /api/v1/animes/1f239e27-08be-4b30-80fe-877283a61e4c/reviews/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedTable: relation "reviews_review" does not exist
LINE 1: SELECT 1 AS "a" FROM "reviews_review" WHERE ("reviews_review...
                             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/apps/contents/viewsets.py", line 111, in review_list
    if reviews.exists():
       ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1286, in exists
    return self.query.has_results(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 648, in has_results
    return compiler.has_results()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1530, in has_results
    return bool(self.execute_sql(SINGLE))
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute
    raise ex.with_traceback(None)
django.db.utils.ProgrammingError: relation "reviews_review" does not exist
LINE 1: SELECT 1 AS "a" FROM "reviews_review" WHERE ("reviews_review...
                             ^
2024-05-28 14:16:31,869:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:16:37,803:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:16:38,856:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:16:46,019:ERROR - django.request log.py (line 241. Internal Server Error: /api/v1/animes/1f239e27-08be-4b30-80fe-877283a61e4c/reviews/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedTable: relation "reviews_review" does not exist
LINE 1: ...ul_count", "reviews_review"."reported_count" FROM "reviews_r...
                                                             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/apps/contents/viewsets.py", line 111, in review_list
    print(reviews)
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 374, in __repr__
    data = list(self[: REPR_OUTPUT_SIZE + 1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1926, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute
    raise ex.with_traceback(None)
django.db.utils.ProgrammingError: relation "reviews_review" does not exist
LINE 1: ...ul_count", "reviews_review"."reported_count" FROM "reviews_r...
                                                             ^
2024-05-28 14:17:18,941:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:17:29,175:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:17:30,432:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:17:43,005:ERROR - django.request log.py (line 241. Internal Server Error: /api/v1/animes/1f239e27-08be-4b30-80fe-877283a61e4c/reviews/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedTable: relation "reviews_review" does not exist
LINE 1: ...ul_count", "reviews_review"."reported_count" FROM "reviews_r...
                                                             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/apps/contents/viewsets.py", line 112, in review_list
    print(reviews)
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 374, in __repr__
    data = list(self[: REPR_OUTPUT_SIZE + 1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1926, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute
    raise ex.with_traceback(None)
django.db.utils.ProgrammingError: relation "reviews_review" does not exist
LINE 1: ...ul_count", "reviews_review"."reported_count" FROM "reviews_r...
                                                             ^
2024-05-28 14:18:15,610:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:18:20,399:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:18:22,264:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:20:38,408:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:20:41,654:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:20:42,641:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:21:02,429:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:21:06,006:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:21:07,238:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:21:11,188:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:21:15,275:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:21:17,215:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:21:27,060:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:21:29,953:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:21:32,313:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:21:36,209:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:21:38,209:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:21:39,303:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:22:08,009:ERROR - django.request log.py (line 241. Internal Server Error: /admin/reviews/review/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedTable: relation "reviews_review" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "reviews_review"
                                          ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 714, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1981, in changelist_view
    cl = self.get_changelist_instance(request)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 862, in get_changelist_instance
    return ChangeList(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/views/main.py", line 145, in __init__
    self.get_results(request)
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/views/main.py", line 312, in get_results
    result_count = paginator.count
                   ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/paginator.py", line 110, in count
    return c()
           ^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 618, in count
    return self.query.get_count(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 618, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 604, in get_aggregation
    result = compiler.execute_sql(SINGLE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute
    raise ex.with_traceback(None)
django.db.utils.ProgrammingError: relation "reviews_review" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "reviews_review"
                                          ^
2024-05-28 14:23:10,869:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:23:29,663:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:23:46,681:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-05-28 14:23:50,486:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:23:51,621:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:23:58,148:WARNING - django.request log.py (line 241. Not Found: /api/v1/animes/1f239e27-08be-4b30-80fe-877283a61e4c/reviews/)
2024-05-28 14:27:02,777:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:27:05,280:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:27:06,590:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:27:18,711:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:27:20,668:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:27:21,548:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:27:26,943:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:27:28,823:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:27:29,758:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:29:39,652:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:29:41,584:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:29:42,483:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:30:00,777:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:30:03,133:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:30:04,395:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:30:11,542:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:30:14,144:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:30:15,740:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:30:19,875:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:30:22,580:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:30:24,225:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:30:30,361:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:30:32,804:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:30:34,506:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:30:39,723:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:30:43,639:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:30:45,811:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:30:51,396:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:30:54,126:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:30:55,515:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:31:10,974:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:31:13,082:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:31:14,229:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:31:19,656:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:31:23,645:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:31:25,281:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:31:27,607:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:31:30,562:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:31:32,174:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:31:40,670:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:31:42,808:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:31:43,753:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:32:46,705:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/animes/1f239e27-08be-4b30-80fe-877283a61e4c/reviews/)
2024-05-28 14:33:30,906:WARNING - django.request log.py (line 241. Bad Request: /api/v1/animes/1f239e27-08be-4b30-80fe-877283a61e4c/reviews/)
2024-05-28 14:43:32,727:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:43:35,000:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:43:35,978:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:43:52,864:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:43:54,868:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:43:55,718:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:44:04,196:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:44:06,518:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:44:07,827:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:44:13,381:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:44:15,759:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:44:17,185:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:44:32,876:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:44:36,845:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:44:37,873:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:44:44,011:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:44:46,001:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:44:46,957:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:45:02,295:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:45:04,185:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:45:05,105:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:49:41,172:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/animes/1f239e27-08be-4b30-80fe-877283a61e4c/reviews/16c108bd-6d74-41f3-a87e-9ba598f99a39/)
2024-05-28 14:50:24,928:WARNING - django.request log.py (line 241. Method Not Allowed: /api/v1/animes/1f239e27-08be-4b30-80fe-877283a61e4c/reviews/16c108bd-6d74-41f3-a87e-9ba598f99a39/)
2024-05-28 14:50:37,206:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:50:39,213:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:50:40,066:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:50:51,661:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:50:54,363:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:50:56,516:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:52:54,550:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:52:56,841:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:52:57,779:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:53:13,104:WARNING - django.request log.py (line 241. Forbidden: /api/v1/animes/1f239e27-08be-4b30-80fe-877283a61e4c/reviews/16c108bd-6d74-41f3-a87e-9ba598f99a39/)
2024-05-28 14:56:40,881:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:56:43,150:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:56:44,129:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:56:47,552:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:56:49,643:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:56:50,895:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 14:56:54,738:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 14:56:57,316:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 14:56:58,389:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 15:18:38,776:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 15:18:41,107:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 15:18:42,037:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 15:19:05,229:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 15:19:07,352:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 15:19:08,280:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 15:19:54,704:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 15:19:57,276:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 15:19:58,566:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 15:20:01,504:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 15:20:03,922:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 15:20:04,936:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 15:20:24,367:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 15:20:26,616:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 15:20:27,832:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 15:20:41,644:ERROR - django.request log.py (line 241. Internal Server Error: /api/v1/animes/1f239e27-08be-4b30-80fe-877283a61e4c/reviews/7dfecccb-e6cc-49e2-a8b3-b163380b1f75/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AnimeViewSet.review_detail() got an unexpected keyword argument 'pk'
2024-05-28 15:21:20,328:ERROR - django.request log.py (line 241. Internal Server Error: /api/v1/animes/1f239e27-08be-4b30-80fe-877283a61e4c/reviews/7dfecccb-e6cc-49e2-a8b3-b163380b1f75/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AnimeViewSet.review_detail() got an unexpected keyword argument 'pk'
2024-05-28 15:21:34,276:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 15:21:37,452:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 15:21:38,739:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 15:21:44,054:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 15:21:46,083:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 15:21:47,543:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 15:21:54,653:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/viewsets.py changed, reloading.)
2024-05-28 15:21:57,166:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 15:21:58,542:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 15:24:56,543:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/serializers.py changed, reloading.)
2024-05-28 15:24:59,035:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 15:25:00,163:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 15:25:04,114:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/serializers.py changed, reloading.)
2024-05-28 15:25:06,077:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 15:25:07,175:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-28 15:25:16,983:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/serializers.py changed, reloading.)
2024-05-28 15:25:19,426:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-28 15:25:20,436:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
