2024-06-03 19:30:14,058:INFO - django.utils.autoreload autoreload.py (line 266. /app/config/settings/base.py changed, reloading.)
2024-06-03 19:30:19,218:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:36:14,856:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 19:36:20,470:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:36:27,326:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 19:36:31,410:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:40:04,728:WARNING - django.request log.py (line 241. Not Found: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/mangas/)
2024-06-03 19:40:07,036:WARNING - django.request log.py (line 241. Not Found: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/mangas/)
2024-06-03 19:41:08,643:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 19:41:13,825:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:41:21,690:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 19:41:26,275:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:41:33,248:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 19:41:37,473:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:42:32,718:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 19:42:37,211:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:43:17,402:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 19:43:22,286:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:43:28,083:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 19:43:34,092:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:44:11,229:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/serializers.py changed, reloading.)
2024-06-03 19:44:15,565:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:44:21,953:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/serializers.py changed, reloading.)
2024-06-03 19:44:27,029:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:44:32,666:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/serializers.py changed, reloading.)
2024-06-03 19:44:37,396:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:44:51,164:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/serializers.py changed, reloading.)
2024-06-03 19:44:54,832:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:44:59,272:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/serializers.py changed, reloading.)
2024-06-03 19:45:04,090:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:45:08,233:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/serializers.py changed, reloading.)
2024-06-03 19:45:15,689:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:45:20,026:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 19:45:25,463:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:45:30,951:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 19:45:35,004:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:45:55,456:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 19:46:00,998:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:46:20,061:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 19:46:25,563:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:46:37,936:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 19:46:43,069:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:47:06,093:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 19:47:11,151:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:47:25,578:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 19:47:30,009:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:48:09,780:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 19:48:13,993:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:48:45,553:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 19:48:50,517:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:49:27,338:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 19:49:31,790:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:49:40,405:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 19:49:45,086:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:49:51,372:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 19:49:57,779:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:50:05,140:ERROR - django.request log.py (line 241. Internal Server Error: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 331, in check_permissions
    for permission in self.get_permissions():
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/apps/persons/viewsets.py", line 56, in get_permissions
    return [AllowAny()]
            ^^^^^^^^
NameError: name 'AllowAny' is not defined
2024-06-03 19:50:10,479:ERROR - django.request log.py (line 241. Internal Server Error: /api/v1/persons/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 331, in check_permissions
    for permission in self.get_permissions():
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/apps/persons/viewsets.py", line 56, in get_permissions
    return [AllowAny()]
            ^^^^^^^^
NameError: name 'AllowAny' is not defined
2024-06-03 19:50:19,798:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 19:50:28,238:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:51:22,794:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/mangas/)
2024-06-03 19:51:55,355:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 19:52:00,559:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:52:04,018:WARNING - django.request log.py (line 241. Not Found: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/mangas/)
2024-06-03 19:52:04,874:WARNING - django.request log.py (line 241. Not Found: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/mangas/)
2024-06-03 19:55:08,172:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 19:55:12,125:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:55:20,927:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 19:55:25,352:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:55:46,740:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 19:55:51,741:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:56:00,300:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 19:56:05,078:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:56:35,481:WARNING - django.request log.py (line 241. Bad Request: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/mangas/)
2024-06-03 19:56:36,991:WARNING - django.request log.py (line 241. Bad Request: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/mangas/)
2024-06-03 19:56:38,414:WARNING - django.request log.py (line 241. Bad Request: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/mangas/)
2024-06-03 19:56:58,375:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 19:57:04,436:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:57:12,951:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 19:57:18,778:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:57:29,788:WARNING - django.request log.py (line 241. Bad Request: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/mangas/)
2024-06-03 19:57:31,835:WARNING - django.request log.py (line 241. Bad Request: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/mangas/)
2024-06-03 19:57:45,338:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 19:57:50,695:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:58:00,012:WARNING - django.request log.py (line 241. Bad Request: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/mangas/)
2024-06-03 19:58:01,496:WARNING - django.request log.py (line 241. Bad Request: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/mangas/)
2024-06-03 19:58:35,771:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 19:58:39,908:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:58:43,364:WARNING - django.request log.py (line 241. Bad Request: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/mangas/)
2024-06-03 19:59:24,024:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 19:59:30,656:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:59:39,207:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 19:59:44,872:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 19:59:48,303:WARNING - django.request log.py (line 241. Bad Request: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/mangas/)
2024-06-03 19:59:49,394:WARNING - django.request log.py (line 241. Bad Request: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/mangas/)
2024-06-03 19:59:50,411:WARNING - django.request log.py (line 241. Bad Request: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/mangas/)
2024-06-03 19:59:51,381:WARNING - django.request log.py (line 241. Bad Request: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/mangas/)
2024-06-03 20:00:02,525:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 20:00:08,652:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 20:00:11,513:WARNING - django.request log.py (line 241. Bad Request: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/mangas/)
2024-06-03 20:00:12,410:WARNING - django.request log.py (line 241. Bad Request: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/mangas/)
2024-06-03 20:00:13,760:WARNING - django.request log.py (line 241. Bad Request: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/mangas/)
2024-06-03 20:00:38,426:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 20:00:44,723:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 20:01:57,252:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 20:02:02,535:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 20:02:07,435:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 20:02:11,701:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 20:02:17,423:WARNING - django.request log.py (line 241. Bad Request: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/mangas/)
2024-06-03 20:02:19,300:WARNING - django.request log.py (line 241. Bad Request: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/mangas/)
2024-06-03 20:02:20,412:WARNING - django.request log.py (line 241. Bad Request: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/mangas/)
2024-06-03 20:02:21,346:WARNING - django.request log.py (line 241. Bad Request: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/mangas/)
2024-06-03 20:02:22,427:WARNING - django.request log.py (line 241. Bad Request: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/mangas/)
2024-06-03 20:02:44,127:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 20:02:49,816:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 20:06:02,318:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/serializers.py changed, reloading.)
2024-06-03 20:06:06,543:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 20:06:13,640:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/serializers.py changed, reloading.)
2024-06-03 20:06:18,112:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 20:06:26,684:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/serializers.py changed, reloading.)
2024-06-03 20:06:30,687:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 20:06:41,549:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/serializers.py changed, reloading.)
2024-06-03 20:06:46,106:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 20:08:23,039:WARNING - django.request log.py (line 241. Bad Request: /api/v1/persons/53622250-be24-4d28-82ed-7034a1beb740/mangas/)
2024-06-03 20:09:22,311:WARNING - django.request log.py (line 241. Bad Request: /api/v1/persons/53622250-be24-4d28-82ed-7034a1beb740/mangas/)
2024-06-03 20:14:13,454:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 20:14:16,967:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 20:18:06,439:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 20:18:09,999:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 20:18:16,066:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 20:18:20,100:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 20:18:36,265:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 20:18:40,826:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 20:18:54,764:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 20:19:00,497:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 20:30:03,861:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/mangas/serializers.py changed, reloading.)
2024-06-03 20:30:08,964:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 20:30:41,032:ERROR - django.request log.py (line 241. Internal Server Error: /api/v1/persons/27dd748f-3ab7-4fab-b09f-cbbda3aeaf1a/mangas/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/rest_framework/fields.py", line 446, in get_attribute
    return get_attribute(instance, self.source_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/fields.py", line 96, in get_attribute
    instance = getattr(instance, attr)
               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Manga' object has no attribute 'get_language_display'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/apps/persons/viewsets.py", line 104, in manga_list
    return paginator.get_paginated_response(serializer.data)
                                            ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 687, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 509, in to_representation
    attribute = field.get_attribute(instance)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/fields.py", line 479, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `media_type` on serializer `MangaMinimalSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `Manga` instance.
Original exception text was: 'Manga' object has no attribute 'get_language_display'.
2024-06-03 20:30:42,229:ERROR - django.request log.py (line 241. Internal Server Error: /api/v1/persons/27dd748f-3ab7-4fab-b09f-cbbda3aeaf1a/mangas/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/rest_framework/fields.py", line 446, in get_attribute
    return get_attribute(instance, self.source_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/fields.py", line 96, in get_attribute
    instance = getattr(instance, attr)
               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Manga' object has no attribute 'get_language_display'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/apps/persons/viewsets.py", line 104, in manga_list
    return paginator.get_paginated_response(serializer.data)
                                            ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 687, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 509, in to_representation
    attribute = field.get_attribute(instance)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/fields.py", line 479, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `media_type` on serializer `MangaMinimalSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `Manga` instance.
Original exception text was: 'Manga' object has no attribute 'get_language_display'.
2024-06-03 20:30:43,660:ERROR - django.request log.py (line 241. Internal Server Error: /api/v1/persons/27dd748f-3ab7-4fab-b09f-cbbda3aeaf1a/mangas/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/rest_framework/fields.py", line 446, in get_attribute
    return get_attribute(instance, self.source_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/fields.py", line 96, in get_attribute
    instance = getattr(instance, attr)
               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Manga' object has no attribute 'get_language_display'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/apps/persons/viewsets.py", line 104, in manga_list
    return paginator.get_paginated_response(serializer.data)
                                            ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 687, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 509, in to_representation
    attribute = field.get_attribute(instance)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/fields.py", line 479, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `media_type` on serializer `MangaMinimalSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `Manga` instance.
Original exception text was: 'Manga' object has no attribute 'get_language_display'.
2024-06-03 20:30:45,179:ERROR - django.request log.py (line 241. Internal Server Error: /api/v1/persons/27dd748f-3ab7-4fab-b09f-cbbda3aeaf1a/mangas/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/rest_framework/fields.py", line 446, in get_attribute
    return get_attribute(instance, self.source_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/fields.py", line 96, in get_attribute
    instance = getattr(instance, attr)
               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Manga' object has no attribute 'get_language_display'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/apps/persons/viewsets.py", line 104, in manga_list
    return paginator.get_paginated_response(serializer.data)
                                            ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 687, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 509, in to_representation
    attribute = field.get_attribute(instance)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/fields.py", line 479, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `media_type` on serializer `MangaMinimalSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `Manga` instance.
Original exception text was: 'Manga' object has no attribute 'get_language_display'.
2024-06-03 20:31:44,231:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/mangas/serializers.py changed, reloading.)
2024-06-03 20:31:48,691:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 20:32:22,144:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/mangas/serializers.py changed, reloading.)
2024-06-03 20:32:26,892:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 20:32:53,135:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/mangas/serializers.py changed, reloading.)
2024-06-03 20:32:58,011:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 20:33:13,033:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/mangas/serializers.py changed, reloading.)
2024-06-03 20:33:16,881:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:23:00,934:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:23:07,884:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:24:13,366:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:24:17,997:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:24:46,462:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:24:50,567:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:25:25,588:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:25:29,991:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:25:44,514:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:25:48,679:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:26:13,665:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:26:18,492:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:27:08,091:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:27:13,452:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:27:46,492:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:27:51,269:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:27:58,121:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:28:02,587:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:28:15,682:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:28:20,488:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:28:40,805:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:28:47,370:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:28:56,673:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:29:00,748:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:29:07,017:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:29:12,915:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:29:19,959:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:29:25,918:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:31:00,689:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 21:31:02,766:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 21:31:07,644:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 21:31:08,726:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 21:31:38,139:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:31:42,160:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:31:56,835:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:32:03,752:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:32:09,322:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:32:13,729:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:32:20,046:WARNING - django.request log.py (line 241. Not Found: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 21:32:31,686:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:32:37,270:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:32:40,795:WARNING - django.request log.py (line 241. Not Found: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 21:32:41,888:WARNING - django.request log.py (line 241. Not Found: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 21:32:42,967:WARNING - django.request log.py (line 241. Not Found: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 21:38:00,819:ERROR - django.request log.py (line 241. Internal Server Error: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/vary.py", line 31, in _view_wrapper
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/apps/persons/viewsets.py", line 146, in picture_list
    if not request.user.role == RoleChoices.CONTRIBUTOR:
           ^^^^^^^^^^^^^^^^^
AttributeError: 'AnonymousUser' object has no attribute 'role'
2024-06-03 21:40:25,103:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:40:31,581:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:40:40,411:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:40:45,816:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:40:50,626:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:40:55,640:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:41:39,383:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:41:45,378:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:41:53,450:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:41:59,025:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:42:07,128:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:42:12,501:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:42:32,948:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:42:38,203:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:42:45,437:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:42:50,289:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:43:05,578:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:43:10,535:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:43:19,782:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:43:26,201:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:43:33,289:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:43:38,198:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:43:45,262:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:43:50,862:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:43:57,608:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:44:02,460:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:44:16,817:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:44:21,518:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:44:32,595:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:44:37,915:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:44:44,251:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:44:48,426:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:44:55,542:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:44:59,648:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:45:06,263:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:45:10,465:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:45:31,246:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 21:45:33,088:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 21:45:34,216:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 21:45:51,125:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:45:55,567:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:46:02,283:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 21:46:04,180:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 21:46:32,172:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 21:46:40,970:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 21:47:23,519:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 21:48:00,289:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/27dd748f-3ab7-4fab-b09f-cbbda3aeaf1a/pictures/)
2024-06-03 21:48:01,725:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/27dd748f-3ab7-4fab-b09f-cbbda3aeaf1a/pictures/)
2024-06-03 21:48:02,744:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/27dd748f-3ab7-4fab-b09f-cbbda3aeaf1a/pictures/)
2024-06-03 21:48:47,883:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:48:53,349:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:48:57,297:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/27dd748f-3ab7-4fab-b09f-cbbda3aeaf1a/pictures/)
2024-06-03 21:48:58,497:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/27dd748f-3ab7-4fab-b09f-cbbda3aeaf1a/pictures/)
2024-06-03 21:48:59,530:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/27dd748f-3ab7-4fab-b09f-cbbda3aeaf1a/pictures/)
2024-06-03 21:49:00,612:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/27dd748f-3ab7-4fab-b09f-cbbda3aeaf1a/pictures/)
2024-06-03 21:49:27,808:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/27dd748f-3ab7-4fab-b09f-cbbda3aeaf1a/pictures/)
2024-06-03 21:49:28,810:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/27dd748f-3ab7-4fab-b09f-cbbda3aeaf1a/pictures/)
2024-06-03 21:49:29,791:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/27dd748f-3ab7-4fab-b09f-cbbda3aeaf1a/pictures/)
2024-06-03 21:50:02,945:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/27dd748f-3ab7-4fab-b09f-cbbda3aeaf1a/pictures/)
2024-06-03 21:50:03,986:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/27dd748f-3ab7-4fab-b09f-cbbda3aeaf1a/pictures/)
2024-06-03 21:50:05,239:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/27dd748f-3ab7-4fab-b09f-cbbda3aeaf1a/pictures/)
2024-06-03 21:50:41,424:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:50:46,762:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:50:50,502:WARNING - django.request log.py (line 241. Not Found: /api/v1/persons/27dd748f-3ab7-4fab-b09f-cbbda3aeaf1a/pictures/)
2024-06-03 21:50:52,151:WARNING - django.request log.py (line 241. Not Found: /api/v1/persons/27dd748f-3ab7-4fab-b09f-cbbda3aeaf1a/pictures/)
2024-06-03 21:50:53,385:WARNING - django.request log.py (line 241. Not Found: /api/v1/persons/27dd748f-3ab7-4fab-b09f-cbbda3aeaf1a/pictures/)
2024-06-03 21:54:31,792:WARNING - django.request log.py (line 241. Not Found: /api/v1/persons/27dd748f-3ab7-4fab-b09f-cbbda3aeaf1a/pictures/)
2024-06-03 21:54:33,255:WARNING - django.request log.py (line 241. Not Found: /api/v1/persons/27dd748f-3ab7-4fab-b09f-cbbda3aeaf1a/pictures/)
2024-06-03 21:54:51,159:WARNING - django.request log.py (line 241. Not Found: /api/v1/persons/27dd748f-3ab7-4fab-b09f-cbbda3aeaf1a/pictures/)
2024-06-03 21:56:20,288:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 21:56:26,182:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:57:10,991:WARNING - django.request log.py (line 241. Not Found: /api/v1/persons/27dd748f-3ab7-4fab-b09f-cbbda3aeaf1a/pictures/)
2024-06-03 21:57:12,156:WARNING - django.request log.py (line 241. Not Found: /api/v1/persons/27dd748f-3ab7-4fab-b09f-cbbda3aeaf1a/pictures/)
2024-06-03 21:58:21,838:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/admin.py changed, reloading.)
2024-06-03 21:58:25,833:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:58:32,578:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/admin.py changed, reloading.)
2024-06-03 21:58:37,819:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 21:58:43,421:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/admin.py changed, reloading.)
2024-06-03 21:58:48,172:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 22:01:49,784:WARNING - django.request log.py (line 241. Not Found: /api/v1/persons/27dd748f-3ab7-4fab-b09f-cbbda3aeaf1a/pictures/)
2024-06-03 22:01:50,876:WARNING - django.request log.py (line 241. Not Found: /api/v1/persons/27dd748f-3ab7-4fab-b09f-cbbda3aeaf1a/pictures/)
2024-06-03 22:01:52,092:WARNING - django.request log.py (line 241. Not Found: /api/v1/persons/27dd748f-3ab7-4fab-b09f-cbbda3aeaf1a/pictures/)
2024-06-03 22:03:17,917:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 22:03:22,770:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 22:03:38,544:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 22:04:02,840:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 22:04:04,179:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 22:04:05,160:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 22:04:13,720:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 22:05:49,171:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 22:05:54,877:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 22:06:02,129:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/create-picture/)
2024-06-03 22:06:03,171:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/create-picture/)
2024-06-03 22:06:04,388:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/create-picture/)
2024-06-03 22:06:23,270:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/create-picture/)
2024-06-03 22:06:24,246:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/create-picture/)
2024-06-03 22:06:53,121:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 22:06:57,148:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 22:07:08,645:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/create-picture/)
2024-06-03 22:07:11,613:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/create-picture/)
2024-06-03 22:07:55,872:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/create-picture/)
2024-06-03 22:07:57,439:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/create-picture/)
2024-06-03 22:08:07,035:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4/create-picture/)
2024-06-03 22:08:24,936:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/create-picture/)
2024-06-03 22:08:26,225:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/create-picture/)
2024-06-03 22:09:50,348:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 22:09:54,756:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 22:10:01,841:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 22:10:07,275:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 22:10:12,757:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/create-picture/)
2024-06-03 22:10:14,296:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/create-picture/)
2024-06-03 22:10:16,078:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/create-picture/)
2024-06-03 22:10:31,224:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/create-picture/)
2024-06-03 22:10:32,815:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/create-picture/)
2024-06-03 22:11:33,747:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 22:11:38,299:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 22:11:45,493:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 22:11:50,104:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 22:12:39,179:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/create-picture/)
2024-06-03 22:12:47,968:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 22:12:52,996:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 22:12:56,607:WARNING - django.request log.py (line 241. Bad Request: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/create-picture/)
2024-06-03 22:12:58,016:WARNING - django.request log.py (line 241. Bad Request: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/create-picture/)
2024-06-03 22:13:22,015:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 22:13:27,529:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 22:13:31,137:WARNING - django.request log.py (line 241. Not Found: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/create-picture/)
2024-06-03 22:13:41,595:WARNING - django.request log.py (line 241. Bad Request: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 22:14:30,784:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 22:14:35,956:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 22:14:47,744:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 22:14:49,537:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 22:15:16,362:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 22:15:27,524:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 22:15:28,840:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 22:15:29,644:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 22:15:30,601:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 22:15:31,462:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 22:15:32,391:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 22:17:11,703:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 22:17:12,905:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 22:17:50,311:WARNING - django.request log.py (line 241. Bad Request: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 22:17:52,038:WARNING - django.request log.py (line 241. Bad Request: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 22:18:24,585:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 22:18:25,925:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 22:18:38,904:WARNING - django.request log.py (line 241. Bad Request: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 22:22:58,441:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 22:23:00,698:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 22:23:01,697:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 22:23:04,249:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 22:23:18,675:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 22:23:25,344:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 22:23:32,378:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 22:23:36,754:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 22:23:45,156:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 22:23:51,850:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 22:23:59,296:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 22:24:03,368:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 22:24:11,513:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 22:24:12,770:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 22:24:13,913:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 22:24:15,711:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/pictures/)
2024-06-03 22:24:50,276:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 22:24:56,450:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 22:25:15,412:WARNING - django.request log.py (line 241. Bad Request: /api/v1/persons/26f541a2-cd76-433d-8f36-b89196f4ee02/create-picture/)
2024-06-03 22:25:28,217:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 22:25:33,142:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 22:29:04,071:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/persons/viewsets.py changed, reloading.)
2024-06-03 22:29:08,391:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
