2024-05-31 14:12:13,124:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 14:16:24,251:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 14:22:23,832:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 18:36:51,816:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 18:36:56,081:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 18:36:57,827:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 18:38:30,162:INFO - django.utils.autoreload autoreload.py (line 266. /app/config/settings/base.py changed, reloading.)
2024-05-31 18:38:39,344:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 18:38:42,353:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 18:39:40,902:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 18:41:02,148:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 18:41:17,140:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 18:41:57,418:INFO - django.utils.autoreload autoreload.py (line 266. /app/config/settings/base.py changed, reloading.)
2024-05-31 18:41:59,728:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 18:42:01,271:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 18:44:07,332:WARNING - django.request log.py (line 241. Not Found: /favicon.ico)
2024-05-31 18:53:41,864:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 18:57:01,677:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 19:02:06,944:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 19:02:39,067:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 19:02:53,609:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 19:03:39,163:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 19:07:42,745:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 19:09:15,873:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 20:20:05,418:INFO - django.utils.autoreload autoreload.py (line 266. /app/config/urls.py changed, reloading.)
2024-05-31 20:20:09,808:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 20:20:12,587:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 20:29:35,984:ERROR - django.request log.py (line 241. Internal Server Error: /api/v1/characters/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/vary.py", line 31, in _view_wrapper
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/apps/characters/viewsets.py", line 48, in list
    return super().list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "/app/apps/characters/viewsets.py", line 33, in get_queryset
    return Character.objects.get_available()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Manager' object has no attribute 'get_available'
2024-05-31 20:30:54,505:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/models.py changed, reloading.)
2024-05-31 20:30:58,542:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 20:31:00,697:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 20:31:08,426:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/models.py changed, reloading.)
2024-05-31 20:31:12,594:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 20:31:14,590:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 20:43:33,790:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/admin.py changed, reloading.)
2024-05-31 20:43:37,190:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 20:43:38,614:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 20:43:44,871:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/admin.py changed, reloading.)
2024-05-31 20:43:48,250:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 20:43:50,122:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 20:43:57,241:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/admin.py changed, reloading.)
2024-05-31 20:44:00,233:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 20:44:02,528:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 20:44:16,049:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/admin.py changed, reloading.)
2024-05-31 20:44:19,058:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 20:44:20,680:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 20:44:27,519:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/admin.py changed, reloading.)
2024-05-31 20:44:30,212:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 20:44:32,282:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 20:44:45,621:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/admin.py changed, reloading.)
2024-05-31 20:44:48,851:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 20:44:50,520:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 20:44:59,657:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/admin.py changed, reloading.)
2024-05-31 20:45:04,405:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 20:45:07,058:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 20:45:14,498:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/admin.py changed, reloading.)
2024-05-31 20:45:17,925:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 20:45:20,014:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 20:45:34,306:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/admin.py changed, reloading.)
2024-05-31 20:45:37,306:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 20:45:40,043:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 20:46:01,376:ERROR - django.request log.py (line 241. Internal Server Error: /api/schema/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/views.py", line 84, in get
    return self._get_schema_response(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/generators.py", line 281, in get_schema
    paths=self.parse(request, public),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/generators.py", line 252, in parse
    operation = view.schema.get_operation(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/openapi.py", line 111, in get_operation
    operation['responses'] = self._get_response_bodies()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/openapi.py", line 1367, in _get_response_bodies
    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/openapi.py", line 1423, in _get_response_for_code
    component = self.resolve_serializer(serializer, direction)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/openapi.py", line 1605, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/openapi.py", line 927, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/openapi.py", line 1020, in _map_basic_serializer
    for field in serializer.fields.values():
                 ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'values'
2024-05-31 20:46:01,860:ERROR - django.request log.py (line 241. Internal Server Error: /api/schema/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/views.py", line 84, in get
    return self._get_schema_response(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/generators.py", line 281, in get_schema
    paths=self.parse(request, public),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/generators.py", line 252, in parse
    operation = view.schema.get_operation(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/openapi.py", line 111, in get_operation
    operation['responses'] = self._get_response_bodies()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/openapi.py", line 1367, in _get_response_bodies
    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/openapi.py", line 1423, in _get_response_for_code
    component = self.resolve_serializer(serializer, direction)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/openapi.py", line 1605, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/openapi.py", line 927, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/openapi.py", line 1020, in _map_basic_serializer
    for field in serializer.fields.values():
                 ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'values'
2024-05-31 20:46:40,202:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 21:06:06,668:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/models.py changed, reloading.)
2024-05-31 21:06:09,708:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 21:06:11,251:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 21:06:24,505:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/models.py changed, reloading.)
2024-05-31 21:06:27,086:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 21:06:28,629:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 21:07:37,010:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/models.py changed, reloading.)
2024-05-31 21:07:44,224:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 21:07:45,853:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 21:07:53,051:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/models.py changed, reloading.)
2024-05-31 21:07:56,505:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 21:07:58,153:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 21:08:09,378:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/models.py changed, reloading.)
2024-05-31 21:08:12,960:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 21:08:14,802:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 21:08:25,714:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/models.py changed, reloading.)
2024-05-31 21:08:29,484:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 21:08:31,246:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 21:18:30,394:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/models.py changed, reloading.)
2024-05-31 21:18:32,864:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 21:18:34,558:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 21:18:40,814:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/models.py changed, reloading.)
2024-05-31 21:18:44,783:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 21:18:46,382:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 21:18:54,560:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/models.py changed, reloading.)
2024-05-31 21:18:57,384:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 21:18:59,417:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 21:19:06,934:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/models.py changed, reloading.)
2024-05-31 21:19:10,563:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 21:19:12,630:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 21:19:20,328:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/models.py changed, reloading.)
2024-05-31 21:19:23,146:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 21:19:24,678:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 21:20:00,813:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/models.py changed, reloading.)
2024-05-31 21:20:04,258:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 21:20:06,661:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 21:20:28,237:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/models.py changed, reloading.)
2024-05-31 21:20:31,416:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 21:20:33,392:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 21:20:49,565:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/models.py changed, reloading.)
2024-05-31 21:20:52,697:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 21:20:54,331:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 21:21:03,824:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/models.py changed, reloading.)
2024-05-31 21:21:07,778:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 21:21:09,858:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 21:21:28,929:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/models.py changed, reloading.)
2024-05-31 21:21:33,490:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 21:21:35,260:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 21:22:25,554:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/models.py changed, reloading.)
2024-05-31 21:22:28,110:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 21:22:29,073:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 21:31:59,136:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/apps.py changed, reloading.)
2024-05-31 21:32:02,102:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 21:32:03,611:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 21:32:23,480:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/admin.py changed, reloading.)
2024-05-31 21:32:26,053:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 21:32:27,544:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 21:32:43,815:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 21:33:40,528:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/models.py changed, reloading.)
2024-05-31 21:33:44,054:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 21:33:45,764:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 21:34:09,787:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/models.py changed, reloading.)
2024-05-31 21:34:12,823:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 21:34:14,671:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 21:34:24,986:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/models.py changed, reloading.)
2024-05-31 21:34:28,534:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 21:34:30,175:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 21:34:38,184:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/models.py changed, reloading.)
2024-05-31 21:34:41,830:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 21:34:43,338:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 21:35:05,028:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/models.py changed, reloading.)
2024-05-31 21:35:09,651:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 21:35:10,801:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 21:35:14,711:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/models.py changed, reloading.)
2024-05-31 21:35:19,543:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 21:35:21,786:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 21:35:41,429:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 21:37:27,359:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/admin.py changed, reloading.)
2024-05-31 21:37:31,191:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 21:37:33,094:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 21:39:00,737:DEBUG - PIL.Image Image.py (line 363. Importing BlpImagePlugin)
2024-05-31 21:39:00,741:DEBUG - PIL.Image Image.py (line 363. Importing BmpImagePlugin)
2024-05-31 21:39:00,741:DEBUG - PIL.Image Image.py (line 363. Importing BufrStubImagePlugin)
2024-05-31 21:39:00,743:DEBUG - PIL.Image Image.py (line 363. Importing CurImagePlugin)
2024-05-31 21:39:00,745:DEBUG - PIL.Image Image.py (line 363. Importing DcxImagePlugin)
2024-05-31 21:39:00,749:DEBUG - PIL.Image Image.py (line 363. Importing DdsImagePlugin)
2024-05-31 21:39:00,772:DEBUG - PIL.Image Image.py (line 363. Importing EpsImagePlugin)
2024-05-31 21:39:00,785:DEBUG - PIL.Image Image.py (line 363. Importing FitsImagePlugin)
2024-05-31 21:39:00,790:DEBUG - PIL.Image Image.py (line 363. Importing FliImagePlugin)
2024-05-31 21:39:00,797:DEBUG - PIL.Image Image.py (line 363. Importing FpxImagePlugin)
2024-05-31 21:39:00,803:DEBUG - PIL.Image Image.py (line 366. Image: failed to import FpxImagePlugin: No module named 'olefile')
2024-05-31 21:39:00,804:DEBUG - PIL.Image Image.py (line 363. Importing FtexImagePlugin)
2024-05-31 21:39:00,819:DEBUG - PIL.Image Image.py (line 363. Importing GbrImagePlugin)
2024-05-31 21:39:00,838:DEBUG - PIL.Image Image.py (line 363. Importing GifImagePlugin)
2024-05-31 21:39:00,843:DEBUG - PIL.Image Image.py (line 363. Importing GribStubImagePlugin)
2024-05-31 21:39:00,849:DEBUG - PIL.Image Image.py (line 363. Importing Hdf5StubImagePlugin)
2024-05-31 21:39:00,853:DEBUG - PIL.Image Image.py (line 363. Importing IcnsImagePlugin)
2024-05-31 21:39:00,870:DEBUG - PIL.Image Image.py (line 363. Importing IcoImagePlugin)
2024-05-31 21:39:00,872:DEBUG - PIL.Image Image.py (line 363. Importing ImImagePlugin)
2024-05-31 21:39:00,882:DEBUG - PIL.Image Image.py (line 363. Importing ImtImagePlugin)
2024-05-31 21:39:00,886:DEBUG - PIL.Image Image.py (line 363. Importing IptcImagePlugin)
2024-05-31 21:39:00,889:DEBUG - PIL.Image Image.py (line 363. Importing JpegImagePlugin)
2024-05-31 21:39:00,894:DEBUG - PIL.Image Image.py (line 363. Importing Jpeg2KImagePlugin)
2024-05-31 21:39:00,897:DEBUG - PIL.Image Image.py (line 363. Importing McIdasImagePlugin)
2024-05-31 21:39:00,901:DEBUG - PIL.Image Image.py (line 363. Importing MicImagePlugin)
2024-05-31 21:39:00,911:DEBUG - PIL.Image Image.py (line 366. Image: failed to import MicImagePlugin: No module named 'olefile')
2024-05-31 21:39:00,912:DEBUG - PIL.Image Image.py (line 363. Importing MpegImagePlugin)
2024-05-31 21:39:00,916:DEBUG - PIL.Image Image.py (line 363. Importing MpoImagePlugin)
2024-05-31 21:39:00,980:DEBUG - PIL.Image Image.py (line 363. Importing MspImagePlugin)
2024-05-31 21:39:00,982:DEBUG - PIL.Image Image.py (line 363. Importing PalmImagePlugin)
2024-05-31 21:39:00,989:DEBUG - PIL.Image Image.py (line 363. Importing PcdImagePlugin)
2024-05-31 21:39:00,996:DEBUG - PIL.Image Image.py (line 363. Importing PcxImagePlugin)
2024-05-31 21:39:00,997:DEBUG - PIL.Image Image.py (line 363. Importing PdfImagePlugin)
2024-05-31 21:39:01,028:DEBUG - PIL.Image Image.py (line 363. Importing PixarImagePlugin)
2024-05-31 21:39:01,032:DEBUG - PIL.Image Image.py (line 363. Importing PngImagePlugin)
2024-05-31 21:39:01,034:DEBUG - PIL.Image Image.py (line 363. Importing PpmImagePlugin)
2024-05-31 21:39:01,035:DEBUG - PIL.Image Image.py (line 363. Importing PsdImagePlugin)
2024-05-31 21:39:01,040:DEBUG - PIL.Image Image.py (line 363. Importing QoiImagePlugin)
2024-05-31 21:39:01,049:DEBUG - PIL.Image Image.py (line 363. Importing SgiImagePlugin)
2024-05-31 21:39:01,052:DEBUG - PIL.Image Image.py (line 363. Importing SpiderImagePlugin)
2024-05-31 21:39:01,058:DEBUG - PIL.Image Image.py (line 363. Importing SunImagePlugin)
2024-05-31 21:39:01,062:DEBUG - PIL.Image Image.py (line 363. Importing TgaImagePlugin)
2024-05-31 21:39:01,065:DEBUG - PIL.Image Image.py (line 363. Importing TiffImagePlugin)
2024-05-31 21:39:01,066:DEBUG - PIL.Image Image.py (line 363. Importing WebPImagePlugin)
2024-05-31 21:39:01,093:DEBUG - PIL.Image Image.py (line 363. Importing WmfImagePlugin)
2024-05-31 21:39:01,095:DEBUG - PIL.Image Image.py (line 363. Importing XbmImagePlugin)
2024-05-31 21:39:01,103:DEBUG - PIL.Image Image.py (line 363. Importing XpmImagePlugin)
2024-05-31 21:39:01,110:DEBUG - PIL.Image Image.py (line 363. Importing XVThumbImagePlugin)
2024-05-31 21:41:29,417:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/routers.py changed, reloading.)
2024-05-31 21:41:34,984:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 21:41:36,984:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 21:41:51,078:DEBUG - PIL.Image Image.py (line 363. Importing BlpImagePlugin)
2024-05-31 21:41:51,081:DEBUG - PIL.Image Image.py (line 363. Importing BmpImagePlugin)
2024-05-31 21:41:51,082:DEBUG - PIL.Image Image.py (line 363. Importing BufrStubImagePlugin)
2024-05-31 21:41:51,084:DEBUG - PIL.Image Image.py (line 363. Importing CurImagePlugin)
2024-05-31 21:41:51,087:DEBUG - PIL.Image Image.py (line 363. Importing DcxImagePlugin)
2024-05-31 21:41:51,093:DEBUG - PIL.Image Image.py (line 363. Importing DdsImagePlugin)
2024-05-31 21:41:51,107:DEBUG - PIL.Image Image.py (line 363. Importing EpsImagePlugin)
2024-05-31 21:41:51,110:DEBUG - PIL.Image Image.py (line 363. Importing FitsImagePlugin)
2024-05-31 21:41:51,115:DEBUG - PIL.Image Image.py (line 363. Importing FliImagePlugin)
2024-05-31 21:41:51,116:DEBUG - PIL.Image Image.py (line 363. Importing FpxImagePlugin)
2024-05-31 21:41:51,121:DEBUG - PIL.Image Image.py (line 366. Image: failed to import FpxImagePlugin: No module named 'olefile')
2024-05-31 21:41:51,122:DEBUG - PIL.Image Image.py (line 363. Importing FtexImagePlugin)
2024-05-31 21:41:51,125:DEBUG - PIL.Image Image.py (line 363. Importing GbrImagePlugin)
2024-05-31 21:41:51,131:DEBUG - PIL.Image Image.py (line 363. Importing GifImagePlugin)
2024-05-31 21:41:51,133:DEBUG - PIL.Image Image.py (line 363. Importing GribStubImagePlugin)
2024-05-31 21:41:51,135:DEBUG - PIL.Image Image.py (line 363. Importing Hdf5StubImagePlugin)
2024-05-31 21:41:51,138:DEBUG - PIL.Image Image.py (line 363. Importing IcnsImagePlugin)
2024-05-31 21:41:51,149:DEBUG - PIL.Image Image.py (line 363. Importing IcoImagePlugin)
2024-05-31 21:41:51,151:DEBUG - PIL.Image Image.py (line 363. Importing ImImagePlugin)
2024-05-31 21:41:51,160:DEBUG - PIL.Image Image.py (line 363. Importing ImtImagePlugin)
2024-05-31 21:41:51,163:DEBUG - PIL.Image Image.py (line 363. Importing IptcImagePlugin)
2024-05-31 21:41:51,165:DEBUG - PIL.Image Image.py (line 363. Importing JpegImagePlugin)
2024-05-31 21:41:51,166:DEBUG - PIL.Image Image.py (line 363. Importing Jpeg2KImagePlugin)
2024-05-31 21:41:51,169:DEBUG - PIL.Image Image.py (line 363. Importing McIdasImagePlugin)
2024-05-31 21:41:51,174:DEBUG - PIL.Image Image.py (line 363. Importing MicImagePlugin)
2024-05-31 21:41:51,177:DEBUG - PIL.Image Image.py (line 366. Image: failed to import MicImagePlugin: No module named 'olefile')
2024-05-31 21:41:51,178:DEBUG - PIL.Image Image.py (line 363. Importing MpegImagePlugin)
2024-05-31 21:41:51,180:DEBUG - PIL.Image Image.py (line 363. Importing MpoImagePlugin)
2024-05-31 21:41:51,209:DEBUG - PIL.Image Image.py (line 363. Importing MspImagePlugin)
2024-05-31 21:41:51,211:DEBUG - PIL.Image Image.py (line 363. Importing PalmImagePlugin)
2024-05-31 21:41:51,216:DEBUG - PIL.Image Image.py (line 363. Importing PcdImagePlugin)
2024-05-31 21:41:51,218:DEBUG - PIL.Image Image.py (line 363. Importing PcxImagePlugin)
2024-05-31 21:41:51,218:DEBUG - PIL.Image Image.py (line 363. Importing PdfImagePlugin)
2024-05-31 21:41:51,236:DEBUG - PIL.Image Image.py (line 363. Importing PixarImagePlugin)
2024-05-31 21:41:51,238:DEBUG - PIL.Image Image.py (line 363. Importing PngImagePlugin)
2024-05-31 21:41:51,239:DEBUG - PIL.Image Image.py (line 363. Importing PpmImagePlugin)
2024-05-31 21:41:51,242:DEBUG - PIL.Image Image.py (line 363. Importing PsdImagePlugin)
2024-05-31 21:41:51,247:DEBUG - PIL.Image Image.py (line 363. Importing QoiImagePlugin)
2024-05-31 21:41:51,249:DEBUG - PIL.Image Image.py (line 363. Importing SgiImagePlugin)
2024-05-31 21:41:51,251:DEBUG - PIL.Image Image.py (line 363. Importing SpiderImagePlugin)
2024-05-31 21:41:51,256:DEBUG - PIL.Image Image.py (line 363. Importing SunImagePlugin)
2024-05-31 21:41:51,258:DEBUG - PIL.Image Image.py (line 363. Importing TgaImagePlugin)
2024-05-31 21:41:51,262:DEBUG - PIL.Image Image.py (line 363. Importing TiffImagePlugin)
2024-05-31 21:41:51,263:DEBUG - PIL.Image Image.py (line 363. Importing WebPImagePlugin)
2024-05-31 21:41:51,271:DEBUG - PIL.Image Image.py (line 363. Importing WmfImagePlugin)
2024-05-31 21:41:51,274:DEBUG - PIL.Image Image.py (line 363. Importing XbmImagePlugin)
2024-05-31 21:41:51,277:DEBUG - PIL.Image Image.py (line 363. Importing XpmImagePlugin)
2024-05-31 21:41:51,283:DEBUG - PIL.Image Image.py (line 363. Importing XVThumbImagePlugin)
2024-05-31 21:41:51,796:ERROR - django.request log.py (line 241. Internal Server Error: /admin/characters/character/add/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute
    raise ex.with_traceback(None)
psycopg.errors.NotNullViolation: null value in column "object_id" of relation "characters_character" violates not-null constraint
DETAIL:  Failing row contains (f9082d0b-7123-4de6-bd02-c75e84d007d6, t, 2024-05-31, 2024-05-31, kikoru-shinomiya, Kikoru Shinomiya, 四ノ宮 キコル, 0, Kikoru is a young prodigy of Kaiju slaying., main, characters/character/kikoru-shinomiya.webp, null, null).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 714, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1941, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1802, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1853, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1257, in save_model
    obj.save()
  File "/app/apps/utils/mixins.py", line 24, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1845, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute
    raise ex.with_traceback(None)
django.db.utils.IntegrityError: null value in column "object_id" of relation "characters_character" violates not-null constraint
DETAIL:  Failing row contains (f9082d0b-7123-4de6-bd02-c75e84d007d6, t, 2024-05-31, 2024-05-31, kikoru-shinomiya, Kikoru Shinomiya, 四ノ宮 キコル, 0, Kikoru is a young prodigy of Kaiju slaying., main, characters/character/kikoru-shinomiya.webp, null, null).
2024-05-31 21:42:41,896:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/routers.py changed, reloading.)
2024-05-31 21:42:45,121:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 21:42:46,764:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 21:44:00,072:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 21:44:05,235:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/migrations/0001_initial.py changed, reloading.)
2024-05-31 21:44:08,418:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 21:44:09,935:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 21:44:15,052:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 21:45:09,996:DEBUG - PIL.Image Image.py (line 363. Importing BlpImagePlugin)
2024-05-31 21:45:09,999:DEBUG - PIL.Image Image.py (line 363. Importing BmpImagePlugin)
2024-05-31 21:45:10,001:DEBUG - PIL.Image Image.py (line 363. Importing BufrStubImagePlugin)
2024-05-31 21:45:10,006:DEBUG - PIL.Image Image.py (line 363. Importing CurImagePlugin)
2024-05-31 21:45:10,008:DEBUG - PIL.Image Image.py (line 363. Importing DcxImagePlugin)
2024-05-31 21:45:10,012:DEBUG - PIL.Image Image.py (line 363. Importing DdsImagePlugin)
2024-05-31 21:45:10,025:DEBUG - PIL.Image Image.py (line 363. Importing EpsImagePlugin)
2024-05-31 21:45:10,031:DEBUG - PIL.Image Image.py (line 363. Importing FitsImagePlugin)
2024-05-31 21:45:10,033:DEBUG - PIL.Image Image.py (line 363. Importing FliImagePlugin)
2024-05-31 21:45:10,034:DEBUG - PIL.Image Image.py (line 363. Importing FpxImagePlugin)
2024-05-31 21:45:10,037:DEBUG - PIL.Image Image.py (line 366. Image: failed to import FpxImagePlugin: No module named 'olefile')
2024-05-31 21:45:10,038:DEBUG - PIL.Image Image.py (line 363. Importing FtexImagePlugin)
2024-05-31 21:45:10,040:DEBUG - PIL.Image Image.py (line 363. Importing GbrImagePlugin)
2024-05-31 21:45:10,043:DEBUG - PIL.Image Image.py (line 363. Importing GifImagePlugin)
2024-05-31 21:45:10,045:DEBUG - PIL.Image Image.py (line 363. Importing GribStubImagePlugin)
2024-05-31 21:45:10,049:DEBUG - PIL.Image Image.py (line 363. Importing Hdf5StubImagePlugin)
2024-05-31 21:45:10,051:DEBUG - PIL.Image Image.py (line 363. Importing IcnsImagePlugin)
2024-05-31 21:45:10,055:DEBUG - PIL.Image Image.py (line 363. Importing IcoImagePlugin)
2024-05-31 21:45:10,058:DEBUG - PIL.Image Image.py (line 363. Importing ImImagePlugin)
2024-05-31 21:45:10,061:DEBUG - PIL.Image Image.py (line 363. Importing ImtImagePlugin)
2024-05-31 21:45:10,065:DEBUG - PIL.Image Image.py (line 363. Importing IptcImagePlugin)
2024-05-31 21:45:10,067:DEBUG - PIL.Image Image.py (line 363. Importing JpegImagePlugin)
2024-05-31 21:45:10,069:DEBUG - PIL.Image Image.py (line 363. Importing Jpeg2KImagePlugin)
2024-05-31 21:45:10,070:DEBUG - PIL.Image Image.py (line 363. Importing McIdasImagePlugin)
2024-05-31 21:45:10,074:DEBUG - PIL.Image Image.py (line 363. Importing MicImagePlugin)
2024-05-31 21:45:10,076:DEBUG - PIL.Image Image.py (line 366. Image: failed to import MicImagePlugin: No module named 'olefile')
2024-05-31 21:45:10,077:DEBUG - PIL.Image Image.py (line 363. Importing MpegImagePlugin)
2024-05-31 21:45:10,079:DEBUG - PIL.Image Image.py (line 363. Importing MpoImagePlugin)
2024-05-31 21:45:10,105:DEBUG - PIL.Image Image.py (line 363. Importing MspImagePlugin)
2024-05-31 21:45:10,107:DEBUG - PIL.Image Image.py (line 363. Importing PalmImagePlugin)
2024-05-31 21:45:10,110:DEBUG - PIL.Image Image.py (line 363. Importing PcdImagePlugin)
2024-05-31 21:45:10,111:DEBUG - PIL.Image Image.py (line 363. Importing PcxImagePlugin)
2024-05-31 21:45:10,112:DEBUG - PIL.Image Image.py (line 363. Importing PdfImagePlugin)
2024-05-31 21:45:10,132:DEBUG - PIL.Image Image.py (line 363. Importing PixarImagePlugin)
2024-05-31 21:45:10,139:DEBUG - PIL.Image Image.py (line 363. Importing PngImagePlugin)
2024-05-31 21:45:10,141:DEBUG - PIL.Image Image.py (line 363. Importing PpmImagePlugin)
2024-05-31 21:45:10,142:DEBUG - PIL.Image Image.py (line 363. Importing PsdImagePlugin)
2024-05-31 21:45:10,144:DEBUG - PIL.Image Image.py (line 363. Importing QoiImagePlugin)
2024-05-31 21:45:10,146:DEBUG - PIL.Image Image.py (line 363. Importing SgiImagePlugin)
2024-05-31 21:45:10,148:DEBUG - PIL.Image Image.py (line 363. Importing SpiderImagePlugin)
2024-05-31 21:45:10,150:DEBUG - PIL.Image Image.py (line 363. Importing SunImagePlugin)
2024-05-31 21:45:10,153:DEBUG - PIL.Image Image.py (line 363. Importing TgaImagePlugin)
2024-05-31 21:45:10,154:DEBUG - PIL.Image Image.py (line 363. Importing TiffImagePlugin)
2024-05-31 21:45:10,154:DEBUG - PIL.Image Image.py (line 363. Importing WebPImagePlugin)
2024-05-31 21:45:10,157:DEBUG - PIL.Image Image.py (line 363. Importing WmfImagePlugin)
2024-05-31 21:45:10,158:DEBUG - PIL.Image Image.py (line 363. Importing XbmImagePlugin)
2024-05-31 21:45:10,160:DEBUG - PIL.Image Image.py (line 363. Importing XpmImagePlugin)
2024-05-31 21:45:10,161:DEBUG - PIL.Image Image.py (line 363. Importing XVThumbImagePlugin)
2024-05-31 21:45:10,299:ERROR - django.request log.py (line 241. Internal Server Error: /admin/characters/character/add/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute
    raise ex.with_traceback(None)
psycopg.errors.NotNullViolation: null value in column "object_id" of relation "characters_character" violates not-null constraint
DETAIL:  Failing row contains (656f7998-b9c8-4cb9-a276-3527bddbb835, t, 2024-05-31, 2024-05-31, kikoru-shinomiya, Kikoru Shinomiya, 四ノ宮 キコル, 0, Kikoru is a young prodigy of Kaiju slaying., main, characters/character/kikoru-shinomiya_aZW0cug.webp, null, null).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 714, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1941, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1802, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1853, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1257, in save_model
    obj.save()
  File "/app/apps/utils/mixins.py", line 24, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1845, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute
    raise ex.with_traceback(None)
django.db.utils.IntegrityError: null value in column "object_id" of relation "characters_character" violates not-null constraint
DETAIL:  Failing row contains (656f7998-b9c8-4cb9-a276-3527bddbb835, t, 2024-05-31, 2024-05-31, kikoru-shinomiya, Kikoru Shinomiya, 四ノ宮 キコル, 0, Kikoru is a young prodigy of Kaiju slaying., main, characters/character/kikoru-shinomiya_aZW0cug.webp, null, null).
2024-05-31 22:20:44,562:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 22:20:48,810:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 22:20:50,326:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 22:21:16,558:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 22:21:32,988:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 22:21:53,145:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 22:28:21,590:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/__init__.py changed, reloading.)
2024-05-31 22:28:24,808:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 22:28:26,420:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 22:29:27,698:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 22:30:59,119:ERROR - django.request log.py (line 241. Internal Server Error: /api/schema/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/views.py", line 84, in get
    return self._get_schema_response(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/generators.py", line 281, in get_schema
    paths=self.parse(request, public),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/generators.py", line 252, in parse
    operation = view.schema.get_operation(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/openapi.py", line 111, in get_operation
    operation['responses'] = self._get_response_bodies()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/openapi.py", line 1367, in _get_response_bodies
    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/openapi.py", line 1423, in _get_response_for_code
    component = self.resolve_serializer(serializer, direction)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/openapi.py", line 1605, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/openapi.py", line 927, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/openapi.py", line 1020, in _map_basic_serializer
    for field in serializer.fields.values():
                 ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'values'
2024-05-31 22:30:59,495:ERROR - django.request log.py (line 241. Internal Server Error: /api/schema/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/views.py", line 84, in get
    return self._get_schema_response(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/generators.py", line 281, in get_schema
    paths=self.parse(request, public),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/generators.py", line 252, in parse
    operation = view.schema.get_operation(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/openapi.py", line 111, in get_operation
    operation['responses'] = self._get_response_bodies()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/openapi.py", line 1367, in _get_response_bodies
    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/openapi.py", line 1423, in _get_response_for_code
    component = self.resolve_serializer(serializer, direction)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/openapi.py", line 1605, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/openapi.py", line 927, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/drf_spectacular/openapi.py", line 1020, in _map_basic_serializer
    for field in serializer.fields.values():
                 ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'values'
2024-05-31 22:31:04,523:WARNING - django.request log.py (line 241. Not Found: /favicon.ico)
2024-05-31 22:32:23,815:DEBUG - PIL.Image Image.py (line 363. Importing BlpImagePlugin)
2024-05-31 22:32:23,818:DEBUG - PIL.Image Image.py (line 363. Importing BmpImagePlugin)
2024-05-31 22:32:23,819:DEBUG - PIL.Image Image.py (line 363. Importing BufrStubImagePlugin)
2024-05-31 22:32:23,823:DEBUG - PIL.Image Image.py (line 363. Importing CurImagePlugin)
2024-05-31 22:32:23,825:DEBUG - PIL.Image Image.py (line 363. Importing DcxImagePlugin)
2024-05-31 22:32:23,828:DEBUG - PIL.Image Image.py (line 363. Importing DdsImagePlugin)
2024-05-31 22:32:23,841:DEBUG - PIL.Image Image.py (line 363. Importing EpsImagePlugin)
2024-05-31 22:32:23,844:DEBUG - PIL.Image Image.py (line 363. Importing FitsImagePlugin)
2024-05-31 22:32:23,846:DEBUG - PIL.Image Image.py (line 363. Importing FliImagePlugin)
2024-05-31 22:32:23,850:DEBUG - PIL.Image Image.py (line 363. Importing FpxImagePlugin)
2024-05-31 22:32:23,855:DEBUG - PIL.Image Image.py (line 366. Image: failed to import FpxImagePlugin: No module named 'olefile')
2024-05-31 22:32:23,856:DEBUG - PIL.Image Image.py (line 363. Importing FtexImagePlugin)
2024-05-31 22:32:23,858:DEBUG - PIL.Image Image.py (line 363. Importing GbrImagePlugin)
2024-05-31 22:32:23,860:DEBUG - PIL.Image Image.py (line 363. Importing GifImagePlugin)
2024-05-31 22:32:23,863:DEBUG - PIL.Image Image.py (line 363. Importing GribStubImagePlugin)
2024-05-31 22:32:23,867:DEBUG - PIL.Image Image.py (line 363. Importing Hdf5StubImagePlugin)
2024-05-31 22:32:23,869:DEBUG - PIL.Image Image.py (line 363. Importing IcnsImagePlugin)
2024-05-31 22:32:23,874:DEBUG - PIL.Image Image.py (line 363. Importing IcoImagePlugin)
2024-05-31 22:32:23,878:DEBUG - PIL.Image Image.py (line 363. Importing ImImagePlugin)
2024-05-31 22:32:23,882:DEBUG - PIL.Image Image.py (line 363. Importing ImtImagePlugin)
2024-05-31 22:32:23,884:DEBUG - PIL.Image Image.py (line 363. Importing IptcImagePlugin)
2024-05-31 22:32:23,888:DEBUG - PIL.Image Image.py (line 363. Importing JpegImagePlugin)
2024-05-31 22:32:23,890:DEBUG - PIL.Image Image.py (line 363. Importing Jpeg2KImagePlugin)
2024-05-31 22:32:23,891:DEBUG - PIL.Image Image.py (line 363. Importing McIdasImagePlugin)
2024-05-31 22:32:23,894:DEBUG - PIL.Image Image.py (line 363. Importing MicImagePlugin)
2024-05-31 22:32:23,897:DEBUG - PIL.Image Image.py (line 366. Image: failed to import MicImagePlugin: No module named 'olefile')
2024-05-31 22:32:23,898:DEBUG - PIL.Image Image.py (line 363. Importing MpegImagePlugin)
2024-05-31 22:32:23,900:DEBUG - PIL.Image Image.py (line 363. Importing MpoImagePlugin)
2024-05-31 22:32:23,923:DEBUG - PIL.Image Image.py (line 363. Importing MspImagePlugin)
2024-05-31 22:32:23,925:DEBUG - PIL.Image Image.py (line 363. Importing PalmImagePlugin)
2024-05-31 22:32:23,929:DEBUG - PIL.Image Image.py (line 363. Importing PcdImagePlugin)
2024-05-31 22:32:23,931:DEBUG - PIL.Image Image.py (line 363. Importing PcxImagePlugin)
2024-05-31 22:32:23,934:DEBUG - PIL.Image Image.py (line 363. Importing PdfImagePlugin)
2024-05-31 22:32:23,951:DEBUG - PIL.Image Image.py (line 363. Importing PixarImagePlugin)
2024-05-31 22:32:23,952:DEBUG - PIL.Image Image.py (line 363. Importing PngImagePlugin)
2024-05-31 22:32:23,953:DEBUG - PIL.Image Image.py (line 363. Importing PpmImagePlugin)
2024-05-31 22:32:23,954:DEBUG - PIL.Image Image.py (line 363. Importing PsdImagePlugin)
2024-05-31 22:32:23,959:DEBUG - PIL.Image Image.py (line 363. Importing QoiImagePlugin)
2024-05-31 22:32:23,963:DEBUG - PIL.Image Image.py (line 363. Importing SgiImagePlugin)
2024-05-31 22:32:23,965:DEBUG - PIL.Image Image.py (line 363. Importing SpiderImagePlugin)
2024-05-31 22:32:23,968:DEBUG - PIL.Image Image.py (line 363. Importing SunImagePlugin)
2024-05-31 22:32:23,970:DEBUG - PIL.Image Image.py (line 363. Importing TgaImagePlugin)
2024-05-31 22:32:23,972:DEBUG - PIL.Image Image.py (line 363. Importing TiffImagePlugin)
2024-05-31 22:32:23,973:DEBUG - PIL.Image Image.py (line 363. Importing WebPImagePlugin)
2024-05-31 22:32:23,980:DEBUG - PIL.Image Image.py (line 363. Importing WmfImagePlugin)
2024-05-31 22:32:23,982:DEBUG - PIL.Image Image.py (line 363. Importing XbmImagePlugin)
2024-05-31 22:32:23,989:DEBUG - PIL.Image Image.py (line 363. Importing XpmImagePlugin)
2024-05-31 22:32:23,993:DEBUG - PIL.Image Image.py (line 363. Importing XVThumbImagePlugin)
2024-05-31 22:36:58,081:ERROR - django.request log.py (line 241. Internal Server Error: /api/v1/characters/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/vary.py", line 31, in _view_wrapper
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/apps/characters/viewsets.py", line 48, in list
    return super().list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 687, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'values'
2024-05-31 22:37:33,046:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/serializers.py changed, reloading.)
2024-05-31 22:37:37,335:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 22:37:40,548:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 22:37:48,309:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/serializers.py changed, reloading.)
2024-05-31 22:37:51,133:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 22:37:52,510:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 22:49:53,775:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-05-31 22:49:56,501:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 22:49:58,106:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 22:52:08,944:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-05-31 22:52:12,718:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 22:52:14,299:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 22:52:22,985:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-05-31 22:52:26,658:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 22:52:28,507:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 22:54:39,327:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/admin.py changed, reloading.)
2024-05-31 22:54:43,716:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 22:54:46,334:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 22:55:18,994:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/admin.py changed, reloading.)
2024-05-31 22:55:22,253:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 22:55:24,340:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 22:57:32,395:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/__init__.py changed, reloading.)
2024-05-31 22:57:35,344:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 22:57:36,941:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-05-31 23:24:30,108:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/admin.py changed, reloading.)
2024-05-31 23:24:33,726:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-05-31 23:24:35,665:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 22:21:27,326:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 22:21:33,634:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 22:21:34,950:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 22:21:50,720:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 22:21:53,928:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 22:21:55,102:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 22:22:04,101:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 22:22:06,297:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 22:22:07,695:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 22:30:55,747:WARNING - django.request log.py (line 241. Not Found: /api/v1/characters/4cc85b9d-2ebb-40df-a5cd-15b207325acb/animes/)
2024-06-02 22:31:41,832:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/characters/4cc85b9d-2ebb-40df-a5cd-15b207325acb/anime/)
2024-06-02 22:32:03,730:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/characters/4cc85b9d-2ebb-40df-a5cd-15b207325acb/anime/)
2024-06-02 22:32:06,036:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/characters/4cc85b9d-2ebb-40df-a5cd-15b207325acb/anime/)
2024-06-02 22:32:07,345:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/characters/4cc85b9d-2ebb-40df-a5cd-15b207325acb/anime/)
2024-06-02 22:32:08,630:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/characters/4cc85b9d-2ebb-40df-a5cd-15b207325acb/anime/)
2024-06-02 22:35:01,314:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 22:35:03,768:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 22:35:06,004:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 22:36:13,404:WARNING - django.request log.py (line 241. Not Found: /favicon.ico)
2024-06-02 22:38:02,802:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/admin.py changed, reloading.)
2024-06-02 22:38:05,136:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 22:38:06,460:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 22:41:49,616:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 22:41:51,630:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 22:41:52,794:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 22:49:38,513:DEBUG - PIL.Image Image.py (line 363. Importing BlpImagePlugin)
2024-06-02 22:49:38,516:DEBUG - PIL.Image Image.py (line 363. Importing BmpImagePlugin)
2024-06-02 22:49:38,516:DEBUG - PIL.Image Image.py (line 363. Importing BufrStubImagePlugin)
2024-06-02 22:49:38,518:DEBUG - PIL.Image Image.py (line 363. Importing CurImagePlugin)
2024-06-02 22:49:38,520:DEBUG - PIL.Image Image.py (line 363. Importing DcxImagePlugin)
2024-06-02 22:49:38,523:DEBUG - PIL.Image Image.py (line 363. Importing DdsImagePlugin)
2024-06-02 22:49:38,535:DEBUG - PIL.Image Image.py (line 363. Importing EpsImagePlugin)
2024-06-02 22:49:38,538:DEBUG - PIL.Image Image.py (line 363. Importing FitsImagePlugin)
2024-06-02 22:49:38,548:DEBUG - PIL.Image Image.py (line 363. Importing FliImagePlugin)
2024-06-02 22:49:38,551:DEBUG - PIL.Image Image.py (line 363. Importing FpxImagePlugin)
2024-06-02 22:49:38,554:DEBUG - PIL.Image Image.py (line 366. Image: failed to import FpxImagePlugin: No module named 'olefile')
2024-06-02 22:49:38,557:DEBUG - PIL.Image Image.py (line 363. Importing FtexImagePlugin)
2024-06-02 22:49:38,561:DEBUG - PIL.Image Image.py (line 363. Importing GbrImagePlugin)
2024-06-02 22:49:38,565:DEBUG - PIL.Image Image.py (line 363. Importing GifImagePlugin)
2024-06-02 22:49:38,566:DEBUG - PIL.Image Image.py (line 363. Importing GribStubImagePlugin)
2024-06-02 22:49:38,568:DEBUG - PIL.Image Image.py (line 363. Importing Hdf5StubImagePlugin)
2024-06-02 22:49:38,571:DEBUG - PIL.Image Image.py (line 363. Importing IcnsImagePlugin)
2024-06-02 22:49:38,575:DEBUG - PIL.Image Image.py (line 363. Importing IcoImagePlugin)
2024-06-02 22:49:38,584:DEBUG - PIL.Image Image.py (line 363. Importing ImImagePlugin)
2024-06-02 22:49:38,587:DEBUG - PIL.Image Image.py (line 363. Importing ImtImagePlugin)
2024-06-02 22:49:38,589:DEBUG - PIL.Image Image.py (line 363. Importing IptcImagePlugin)
2024-06-02 22:49:38,597:DEBUG - PIL.Image Image.py (line 363. Importing JpegImagePlugin)
2024-06-02 22:49:38,598:DEBUG - PIL.Image Image.py (line 363. Importing Jpeg2KImagePlugin)
2024-06-02 22:49:38,600:DEBUG - PIL.Image Image.py (line 363. Importing McIdasImagePlugin)
2024-06-02 22:49:38,602:DEBUG - PIL.Image Image.py (line 363. Importing MicImagePlugin)
2024-06-02 22:49:38,605:DEBUG - PIL.Image Image.py (line 366. Image: failed to import MicImagePlugin: No module named 'olefile')
2024-06-02 22:49:38,606:DEBUG - PIL.Image Image.py (line 363. Importing MpegImagePlugin)
2024-06-02 22:49:38,609:DEBUG - PIL.Image Image.py (line 363. Importing MpoImagePlugin)
2024-06-02 22:49:38,642:DEBUG - PIL.Image Image.py (line 363. Importing MspImagePlugin)
2024-06-02 22:49:38,644:DEBUG - PIL.Image Image.py (line 363. Importing PalmImagePlugin)
2024-06-02 22:49:38,654:DEBUG - PIL.Image Image.py (line 363. Importing PcdImagePlugin)
2024-06-02 22:49:38,656:DEBUG - PIL.Image Image.py (line 363. Importing PcxImagePlugin)
2024-06-02 22:49:38,658:DEBUG - PIL.Image Image.py (line 363. Importing PdfImagePlugin)
2024-06-02 22:49:38,682:DEBUG - PIL.Image Image.py (line 363. Importing PixarImagePlugin)
2024-06-02 22:49:38,691:DEBUG - PIL.Image Image.py (line 363. Importing PngImagePlugin)
2024-06-02 22:49:38,693:DEBUG - PIL.Image Image.py (line 363. Importing PpmImagePlugin)
2024-06-02 22:49:38,694:DEBUG - PIL.Image Image.py (line 363. Importing PsdImagePlugin)
2024-06-02 22:49:38,697:DEBUG - PIL.Image Image.py (line 363. Importing QoiImagePlugin)
2024-06-02 22:49:38,699:DEBUG - PIL.Image Image.py (line 363. Importing SgiImagePlugin)
2024-06-02 22:49:38,705:DEBUG - PIL.Image Image.py (line 363. Importing SpiderImagePlugin)
2024-06-02 22:49:38,707:DEBUG - PIL.Image Image.py (line 363. Importing SunImagePlugin)
2024-06-02 22:49:38,709:DEBUG - PIL.Image Image.py (line 363. Importing TgaImagePlugin)
2024-06-02 22:49:38,712:DEBUG - PIL.Image Image.py (line 363. Importing TiffImagePlugin)
2024-06-02 22:49:38,713:DEBUG - PIL.Image Image.py (line 363. Importing WebPImagePlugin)
2024-06-02 22:49:38,724:DEBUG - PIL.Image Image.py (line 363. Importing WmfImagePlugin)
2024-06-02 22:49:38,728:DEBUG - PIL.Image Image.py (line 363. Importing XbmImagePlugin)
2024-06-02 22:49:38,734:DEBUG - PIL.Image Image.py (line 363. Importing XpmImagePlugin)
2024-06-02 22:49:38,738:DEBUG - PIL.Image Image.py (line 363. Importing XVThumbImagePlugin)
2024-06-02 22:54:54,681:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 22:54:59,560:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 22:55:01,604:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 22:55:08,767:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 22:55:12,495:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 22:55:14,666:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 22:55:20,875:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 22:55:23,119:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 22:55:24,695:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 22:55:33,644:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 22:55:36,502:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 22:55:38,131:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 22:55:45,007:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 22:55:48,201:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 22:55:49,897:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 22:57:31,381:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 22:57:34,370:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 22:57:36,178:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 22:57:48,003:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 22:57:50,711:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 22:57:52,291:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 22:59:01,161:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 22:59:04,015:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 22:59:05,469:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 22:59:20,563:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 22:59:23,211:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 22:59:24,648:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 22:59:33,435:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 22:59:38,243:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 22:59:39,719:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 22:59:46,405:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 22:59:49,716:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 22:59:51,312:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 22:59:55,317:WARNING - django.request log.py (line 241. Not Found: /api/v1/characters/4cc85b9d-2ebb-40df-a5cd-15b207325acb/anime/)
2024-06-02 23:00:15,378:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:00:17,766:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:00:19,318:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:03:59,970:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/models.py changed, reloading.)
2024-06-02 23:04:03,266:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:04:04,152:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:04:13,384:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/models.py changed, reloading.)
2024-06-02 23:04:16,463:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:04:18,013:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:09:27,093:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/models.py changed, reloading.)
2024-06-02 23:09:29,632:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:09:31,333:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:10:12,426:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:10:29,656:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:12:04,578:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/models.py changed, reloading.)
2024-06-02 23:12:06,931:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:12:08,129:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:12:14,633:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/models.py changed, reloading.)
2024-06-02 23:12:16,940:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:12:18,273:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:13:12,716:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:13:14,909:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:13:16,148:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:13:40,301:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:14:11,932:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/models.py changed, reloading.)
2024-06-02 23:14:14,595:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:14:15,683:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:14:29,797:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:14:45,009:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:22:15,631:ERROR - django.request log.py (line 241. Internal Server Error: /admin/utils/picture/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedTable: relation "utils_picture" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "utils_picture"
                                          ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 714, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1981, in changelist_view
    cl = self.get_changelist_instance(request)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 862, in get_changelist_instance
    return ChangeList(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/views/main.py", line 145, in __init__
    self.get_results(request)
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/views/main.py", line 312, in get_results
    result_count = paginator.count
                   ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/paginator.py", line 110, in count
    return c()
           ^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 618, in count
    return self.query.get_count(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 618, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 604, in get_aggregation
    result = compiler.execute_sql(SINGLE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute
    raise ex.with_traceback(None)
django.db.utils.ProgrammingError: relation "utils_picture" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "utils_picture"
                                          ^
2024-06-02 23:23:14,036:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:23:17,290:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:23:19,356:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:23:24,152:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:23:27,038:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:23:28,616:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:23:47,577:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:23:51,139:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:23:53,652:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:23:59,809:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:24:03,365:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:24:05,001:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:24:08,532:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:24:11,318:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:24:13,076:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:24:39,751:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:24:43,697:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:24:46,731:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:24:54,880:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:24:57,528:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:24:59,690:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:25:11,309:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:25:16,516:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:25:18,502:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:25:35,180:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:25:38,950:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:25:41,163:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:26:04,399:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:26:07,651:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:26:10,222:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:26:19,191:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:26:22,843:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:26:24,593:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:26:35,853:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:26:39,557:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:26:41,418:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:26:56,984:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:27:01,419:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:27:04,952:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:27:16,219:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:27:20,378:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:27:22,871:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:27:33,963:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:27:37,476:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:27:38,970:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:28:08,659:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:28:12,393:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:28:14,936:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:28:22,228:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:28:25,318:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:28:26,905:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:30:14,115:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:30:17,532:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:30:19,502:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:30:27,743:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:30:31,811:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:30:34,702:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:30:44,962:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:30:48,016:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:30:49,788:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:30:57,439:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/characters/4cc85b9d-2ebb-40df-a5cd-15b207325acb/anime/)
2024-06-02 23:30:59,539:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/characters/4cc85b9d-2ebb-40df-a5cd-15b207325acb/anime/)
2024-06-02 23:31:00,904:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/characters/4cc85b9d-2ebb-40df-a5cd-15b207325acb/anime/)
2024-06-02 23:31:01,956:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/characters/4cc85b9d-2ebb-40df-a5cd-15b207325acb/anime/)
2024-06-02 23:31:10,236:WARNING - django.request log.py (line 241. Unauthorized: /api/v1/characters/4cc85b9d-2ebb-40df-a5cd-15b207325acb/anime/)
2024-06-02 23:31:32,457:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:31:35,887:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:31:37,717:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:31:44,677:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:31:47,460:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:31:49,039:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:31:54,112:ERROR - django.request log.py (line 241. Internal Server Error: /api/v1/characters/4cc85b9d-2ebb-40df-a5cd-15b207325acb/anime/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/apps/characters/viewsets.py", line 77, in anime_for_character
    anime_id = character_anime.values("anime_id", flat=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1358, in values
    clone = self._values(*fields, **expressions)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1351, in _values
    clone = clone.annotate(**expressions)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1630, in annotate
    return self._annotate(args, kwargs, select=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1640, in _annotate
    self._validate_values_are_expressions(
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1995, in _validate_values_are_expressions
    raise TypeError(
TypeError: QuerySet.annotate() received non-expression(s): True.
2024-06-02 23:32:33,503:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:32:37,480:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:32:39,769:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:32:49,793:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:32:53,786:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:32:56,202:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:34:10,048:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:34:15,017:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:34:16,960:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:34:25,172:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:34:28,548:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:34:30,563:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:34:41,601:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:34:46,095:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:34:47,961:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:37:49,634:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:37:52,714:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:37:54,756:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:38:07,324:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:38:09,785:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:38:12,326:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:38:46,496:ERROR - django.request log.py (line 241. Internal Server Error: /api/v1/characters/4cc85b9d-2ebb-40df-a5cd-15b207325acb/anime/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/apps/characters/viewsets.py", line 81, in anime_for_character
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
           ^
TypeError: 'Anime' object is not iterable
2024-06-02 23:39:06,863:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:39:09,693:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:39:12,009:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:39:58,744:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:40:02,132:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:40:04,632:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:40:13,759:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:40:17,903:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:40:20,261:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:40:29,282:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:40:33,089:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:40:35,612:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:40:43,745:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:40:47,516:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:40:49,455:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:42:24,614:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:42:29,192:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:42:30,842:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:42:48,725:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:42:51,778:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:42:53,556:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:43:03,721:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:43:06,692:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:43:08,672:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-02 23:43:16,188:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/viewsets.py changed, reloading.)
2024-06-02 23:43:20,427:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-02 23:43:22,303:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 13:42:48,459:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 13:43:00,754:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 13:43:02,480:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 13:44:27,902:WARNING - django.request log.py (line 241. Not Found: /favicon.ico)
2024-06-03 13:49:30,686:INFO - django.utils.autoreload autoreload.py (line 266. /app/config/urls.py changed, reloading.)
2024-06-03 13:49:37,440:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 13:50:02,928:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 13:52:25,578:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/models.py changed, reloading.)
2024-06-03 13:52:28,327:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 13:52:30,310:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 13:52:37,037:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/models.py changed, reloading.)
2024-06-03 13:52:39,252:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 13:52:40,366:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 13:53:52,363:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/utils/models.py changed, reloading.)
2024-06-03 13:53:55,433:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 13:53:57,286:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 13:54:03,509:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/utils/models.py changed, reloading.)
2024-06-03 13:54:06,851:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 13:54:08,243:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 13:54:18,355:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/utils/models.py changed, reloading.)
2024-06-03 13:54:21,601:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 13:54:22,021:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 13:54:39,483:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/utils/models.py changed, reloading.)
2024-06-03 13:54:42,782:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 13:54:44,140:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 13:54:49,864:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/utils/models.py changed, reloading.)
2024-06-03 13:54:52,495:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 13:54:53,867:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 13:57:54,837:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/utils/models.py changed, reloading.)
2024-06-03 13:57:58,022:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 13:57:59,311:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 13:58:12,099:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 13:59:20,179:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:00:46,252:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/models.py changed, reloading.)
2024-06-03 14:00:49,439:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:00:50,860:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 14:00:58,764:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/characters/models.py changed, reloading.)
2024-06-03 14:01:01,502:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:01:02,851:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 14:01:13,579:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:02:08,291:INFO - django.utils.autoreload autoreload.py (line 266. /app/config/settings/base.py changed, reloading.)
2024-06-03 14:02:11,387:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:02:13,112:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 14:03:46,321:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:04:07,390:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:04:27,276:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/utils/admin.py changed, reloading.)
2024-06-03 14:04:31,635:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:04:33,625:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 14:04:37,993:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/utils/admin.py changed, reloading.)
2024-06-03 14:04:41,375:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:04:43,208:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 14:04:51,563:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/utils/admin.py changed, reloading.)
2024-06-03 14:04:54,396:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:04:56,892:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 14:15:06,246:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/utils/models.py changed, reloading.)
2024-06-03 14:15:09,892:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:15:11,731:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 14:15:25,014:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/utils/models.py changed, reloading.)
2024-06-03 14:15:29,469:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:15:32,405:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 14:15:43,135:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/utils/models.py changed, reloading.)
2024-06-03 14:15:47,035:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:15:47,543:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 14:15:50,198:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/utils/models.py changed, reloading.)
2024-06-03 14:15:54,145:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:15:55,638:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 14:16:04,497:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/utils/models.py changed, reloading.)
2024-06-03 14:16:08,431:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:16:10,126:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 14:16:19,179:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/utils/models.py changed, reloading.)
2024-06-03 14:16:23,429:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:16:25,574:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 14:16:34,620:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/utils/models.py changed, reloading.)
2024-06-03 14:16:37,720:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:16:39,533:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 14:17:08,523:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/utils/models.py changed, reloading.)
2024-06-03 14:17:11,699:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:17:13,817:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 14:19:19,289:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/utils/models.py changed, reloading.)
2024-06-03 14:19:22,218:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:19:24,268:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 14:19:30,921:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/utils/models.py changed, reloading.)
2024-06-03 14:19:34,408:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:19:36,390:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 14:19:45,098:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/utils/models.py changed, reloading.)
2024-06-03 14:19:48,861:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:19:51,521:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 14:20:07,177:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:20:26,198:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:23:10,869:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/utils/models.py changed, reloading.)
2024-06-03 14:23:13,534:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:23:16,094:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 14:23:36,784:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/utils/models.py changed, reloading.)
2024-06-03 14:23:39,679:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:23:41,542:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 14:23:47,677:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/utils/models.py changed, reloading.)
2024-06-03 14:23:50,355:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:23:51,855:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 14:25:41,282:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/utils/models.py changed, reloading.)
2024-06-03 14:25:44,153:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:25:45,494:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 14:25:56,978:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/utils/models.py changed, reloading.)
2024-06-03 14:25:59,526:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:26:01,405:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 14:26:50,013:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/utils/models.py changed, reloading.)
2024-06-03 14:26:53,084:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:26:54,290:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 14:27:00,480:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/utils/models.py changed, reloading.)
2024-06-03 14:27:02,560:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:27:03,803:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 14:33:35,752:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/utils/models.py changed, reloading.)
2024-06-03 14:33:38,620:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:33:39,936:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 14:34:02,103:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/utils/models.py changed, reloading.)
2024-06-03 14:34:04,754:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:34:05,104:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 14:34:14,757:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/utils/models.py changed, reloading.)
2024-06-03 14:34:17,111:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:34:18,829:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 14:34:34,541:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/utils/models.py changed, reloading.)
2024-06-03 14:34:37,137:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:34:38,374:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 14:35:50,539:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/utils/models.py changed, reloading.)
2024-06-03 14:35:53,369:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:35:54,669:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 14:39:09,626:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/utils/models.py changed, reloading.)
2024-06-03 14:39:12,612:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:39:14,263:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 14:42:10,118:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:42:11,681:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-06-03 14:46:54,335:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-06-03 14:46:55,729:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
